### ISSUE TITLE
Ctrl+hover issue

### ISSUE THREAD

**Issue by menagerie198** [nothingislost/obsidian-hover-editor#10]
I have the Recent Files plugin open in a side pane, and set to need Ctrl to view a popup on hover. Since Hover Editor when I hold Ctrl and move the pointer over to a file in the Recent Files pane (in order to view the popup, popup scrolls through the list of recent files.  Very jumpy and disconcerting.

**Comment by nothingislost** [comment]
Check out https://github.com/nothingislost/obsidian-hover-editor/releases/tag/0.2.0. It should help resolve this issue.

**Comment by menagerie198** [comment]
Thanks, that has sorted it.
