### ISSUE TITLE
[BUG] Open Hover Note when changing Workspaces (Core Plugin)

### ISSUE THREAD

**Issue by FelipeRearden** [nothingislost/obsidian-hover-editor#109]
Hello @nothingislost !!!!!

I think I found a bug :)

If I have a Hover Note open in Workspace A **and when I switch from Workspace A to Workspace B** the Hover Note updates to an  empty. 
- In other words, Hover notes are closing  when we change workspaces

img 1 has a hover note open in  workspace "WK1" (look at top-right)

![q1](https://user-images.githubusercontent.com/85180696/163723593-1801d580-7fe5-4bf6-8925-3ae7ff417496.png)

img 2 has an empty hover note after I switch to Workspace "Mood" (look at top-right) 

![q2](https://user-images.githubusercontent.com/85180696/163723603-888346cd-1175-45a4-b418-94439bab4735.png)

Sorry for the mess, its my test vault :)

## Steps to reproduce

1- Open a workspace
2- Open a Hover Note
3- Load Workspaces -> Choose another Workspace

---

Let me know if something is not clear !

Thanks for reading this !!!!! I hope is an easy one :pray: 

Have a great day!!!!

**Comment by wenlzhang** [comment]
I also noticed something like this.

**Comment by FelipeRearden** [comment]
Working perfect on version `0.9.2` Obsidian `0.14.6` and Obsidian Mobile on iOS 

Thank you very much @nothingislost and @pjeby !!!!!!!!!!!
