### ISSUE TITLE
Cannot open file in 2nd pane

### ISSUE THREAD

**Issue by DutchPete** [nothingislost/obsidian-hover-editor#11]
Let's say I have only 1 file open in a pane. If I then go to the Obsidian file explorer, hover over another file, then hold Cmd (⌘) and click on it in order to open it in a 2<sup>nd</sup> pane next to the 1<sup>st</sup> one, it does not happen. What I do get is that a 2<sup>nd</sup> copy of the popover occurs over the 1<sup>st</sup> popover.

I also tried left-clicking the 2<sup>nd</sup> file to be open, but left-click is dead.

**Comment by nothingislost** [comment]
Check out https://github.com/nothingislost/obsidian-hover-editor/releases/tag/0.2.0. It should resolve this issue.

**Comment by DutchPete** [comment]
I have Hover Editor 0.1.2 installed via BRAT, but clicking on *Check for updates* in the plug-in settings does not update HE.

**Comment by DutchPete** [comment]
@HEmile thanks, that works. This is the 1st time I do it this way.
