### ISSUE TITLE
Suggest adding the option to close the hover enhancement and turn the active page that is open into a hover page.

### ISSUE THREAD

**Issue by MILKMILKKING** [nothingislost/obsidian-hover-editor#12]
Thank you for designing the plugin, very good idea!
Could you add a new option and a new feature.
Suggest a new option: turn off hover enhancements and set a quick key for this option.
This would have the advantage that sometimes the hover enhancements are not needed for a while and can be turned off quickly without having to go digging through the settings and turning the whole plugin off.

A new feature is suggested: turn the active page that is open into a hover page.
The advantage of this is that there are notes that fall under the category of needing to check them out, but don't want to take up too much screen space. This will directly shrink the page being opened and make it easy to put it aside for viewing.

Thanks again for the idea, it's really great.

**Comment by nothingislost** [comment]
Your second idea is now available in https://github.com/nothingislost/obsidian-hover-editor/releases/tag/0.3.0

For the disable feature, why would you revert to the native popover functionality? Just curious what the benefit of using the native popover would be in your opinion.

**Comment by MILKMILKKING** [comment]
Thanks for the update, now please ignore my first request as it was still at version 0.12 and not perfect, now it is running very well! Thank you!
