### ISSUE TITLE
Hover editor stops Tag Wrangler hover over tags

### ISSUE THREAD

**Issue by dcoales** [nothingislost/obsidian-hover-editor#123]
With the Tag Wrangler plugin you can create a page with an alias equal to a tag.  Then when you hover over the tag the page with that alias appears in the hover window.  However this doesn't work if the Hover Editor plugin is active.  Is there any way that Hover Editor could work with Tag Wrangler to keep this functionality.

Thanks.

**Comment by pjeby** [comment]
I'm not able to reproduce this problem; what are you hovering over, precisely?  Source mode?  Live Preview?  Reading mode?  Legacy editor?  The tag pane?  Something else altogether?

**Comment by dcoales** [comment]
I've also just tried to repeat the issue myself and can't.  I've no idea what I was doing wrong the first time.  Apologies for wasting your time.  Loving the plugin though.  Many thanks.
