### ISSUE TITLE
Some Actions Can Cause Header Of Hover Editor Window Get Stuck Into Obsidian Header

### ISSUE THREAD

**Issue by Archie-2021** [nothingislost/obsidian-hover-editor#136]
![image](https://user-images.githubusercontent.com/85870778/169887435-2a8ce466-1b75-4c84-b4c0-8616c5c4fc70.png)

Like this, this happened for example because I minimized the window (to bottom) moved the window up and then undu the minimize. And there is nothing that can be done to fix it , only to restart to app

**Comment by dcoales** [comment]
I get the same issue if I open Obsidian on a large monitor, resize the hover window to be almost as tall as the Obsidian window and then move obsidian to a smaller monitor.  In fact this happens automatically when my laptop goes into screen saver mode for seem reason - all windows move to the laptop screen when it wakes up again - and my hover windows are now stuck.

**Comment by pjeby** [comment]
Hover Editor 0.11.7 contains a change that should fix this issue; let us know if it still persists.
