### ISSUE TITLE
FR: Maintain selection history across multiple popover instances

### ISSUE THREAD

**Issue by HEmile** [nothingislost/obsidian-hover-editor#14]
Steps:
1. Open hover under link
2. In that new hover, open another hover
3. That second hover has keyboard focus! 
4. Now close the second hover
5. Now the main page has the keyboard focus instead of the first hover:

https://user-images.githubusercontent.com/1289165/157897506-edc71556-9c7c-495a-aa37-7036924d7e0d.mov

This may be hard to fix, and it's not a big deal, but thought I'd report it anyways.

**Comment by nothingislost** [comment]
Yeah, this is a tricky one. The logic that restores the selection used getMostRecentLeaf() which calls iterateRootLeaves() to look for the most recently active leaf.

Popovers are not technically in the root split (they just pretend to be) so they won't show up in iterateRootLeaves(). If I make them show up in iterateRootLeaves() then I have a whole new set of problems to deal with :)

I'll think about this one and see if there's anything I can do.
