### ISSUE TITLE
Doesn't work with Kanban

### ISSUE THREAD

**Issue by asmagen** [nothingislost/obsidian-hover-editor#141]
How can the following issue be fixed, where each kanban breaks into thin columns although there is enough width for the full column to be presented well with Hover Editor. Even after I increased the Hover Editor settings to be as wide as the whole screen, it still does that.
Thanks!
<img width="585" alt="Screen Shot 2022-06-05 at 8 18 43 AM" src="https://user-images.githubusercontent.com/11299568/172050043-a372f115-3660-4815-9281-87031c1f5c66.png">

**Comment by pjeby** [comment]
As far as I know, Kanban boards have fixed-width columns whether they are in the main window, sidebar, or a popover.  Have you tried setting the board to use wider columns?

**Comment by asmagen** [comment]
Yes, it doesn't fix it.
________________________________

**Comment by pjeby** [comment]
I'm not able to reproduce this problem -- all of my Kanban boards work fine in hover editors.  Can you send the text of the note that has this issue, and a copy of your main Kanban settings?  Also, are you using a third-party theme, or Obsidian's default theme?

**Comment by pjeby** [comment]
If at some point you can provide the data we need in order to investigate this, feel free to respond here and I will reopen the issue.
