### ISSUE TITLE
hovering over links in longer notes automatically jumps me to the top of the page instead of creating a hover editor preview 

### ISSUE THREAD

**Issue by jacksonspindle** [nothingislost/obsidian-hover-editor#142]
I notice this happens a lot when on longer notes with lots of links in them... when I hover over a link instead of getting a hover editor preview it automatically jumps me to the top of the page instead....

https://user-images.githubusercontent.com/65312761/173556748-0cd2a8b4-ccba-4c63-a6da-a92bad6423e1.mov

**Comment by AnweshGangula** [comment]
Same issue with me too

**Comment by pjeby** [comment]
I'm not able to reproduce this: can you share your hover editor settings, and also any editor settings?  Is it only in reading view, or also live preview?  Source mode?  Does it happen with the stock theme or in the sandbox vault?  We need to be able to reproduce the problem in order to figure out what's happening.

**Comment by jacksonspindle** [comment]
Thanks for getting back to me! Below are some answers to those questions and screenshots of the my current hover editor and editor settings. Also, I only ever notice this bug in my longer notes that have lots of links... in order to replicate it you may need to try on a longer note - short notes don't seem to have this problem (possibly because there is no room to jump up to in the first place?). Let me know if you need anything else.

1. It seems to only occur in Reading View for me-- the issue doesn't occur in live preview mode 
2. It happens with any theme I've used including the default obsidian theme 

3. **Hover Editor settings**: 
<img width="1161" alt="Screen Shot 2022-07-04 at 7 23 17 PM" src="https://user-images.githubusercontent.com/65312761/177224894-f9f144cb-dbfb-41b6-9133-f7d80f4e8742.png">
<img width="1140" alt="Screen Shot 2022-07-04 at 7 23 38 PM" src="https://user-images.githubusercontent.com/65312761/177224914-b8bfce37-9883-45be-b050-47790dd3851b.png">

4. **Editor settings**: 
<img width="1159" alt="Screen Shot 2022-07-04 at 7 24 27 PM" src="https://user-images.githubusercontent.com/65312761/177224962-abf0c9ed-2e6d-4dea-ae66-bf2dbad2720f.png">
<img width="1144" alt="Screen Shot 2022-07-04 at 7 25 01 PM" src="https://user-images.githubusercontent.com/65312761/177224996-d16a5eb2-22d6-4440-be9a-37b7482228c8.png">
<img width="1144" alt="Screen Shot 2022-07-04 at 7 25 23 PM" src="https://user-images.githubusercontent.com/65312761/177225021-b5668cce-6b5d-4f76-9e96-95b8af3950e2.png">

**Comment by nothingislost** [comment]
I can't replicate this either, even on very long notes. Could you try replicating this with all plugins disabled except for Hover Editor and see if it persists? If it doesn't occur with the other plugins disabled, we'll need you to narrow down which plugin is causing the adverse reaction.

**Comment by Masktial** [comment]
"Bartender", perhaps.
 I closed the plugin, the problem just gone.

**Comment by pjeby** [comment]
Updating to Hover Editor 0.11.7 and Obsidian 1.0.3 may fix this issue for anyone who is still having it; if it persists after update and restart, please let us know.
