### ISSUE TITLE
Hover editor conflicts with Open in new window

### ISSUE THREAD

**Issue by AndyLiu9** [nothingislost/obsidian-hover-editor#143]
After updating to insider 0.15.0, if I turn on hover editor, then open in new window doesn’t work as shown:
![1F875A4F-480F-4EC1-BA60-525522D8966F](https://user-images.githubusercontent.com/88693956/173729535-1578af6b-5f9d-4ac1-9b16-8b11dbf63ece.png)

**Comment by nothingislost** [comment]
If you want to test out the latest beta, use BRAT to upgrade to version 0.10.0.

Otherwise, if you want to stick to the current community store version, install and enable the Pane Relief plugin to prevent this issue for now

**Comment by AndyLiu9** [comment]
Thanks for your response. I haven’t updated HE to the beta version so far, but with 0.15.3, New Window now works fine. So I just close this issue, thanks again!
