### ISSUE TITLE
Insert(input) in Vim mode could lose focus and and conduce hover editor window closed

### ISSUE THREAD

**Issue by Palvehelmed** [nothingislost/obsidian-hover-editor#144]
It happens from time to time when I input and the window closed automatically. 

This doesn't always happen but still has a pretty considerable probability in my case, I assume it could be around about one quarter. I'm sure the pointer is in the frame of the window, but it disappears when I type which I assume has some relationship with Vim mode.

It would be highly appreciated if this could be fixed soon. I love this extension so much and I use it all the time. Open auto pin when opening a window could be a bit cumbersome to me.

BR.

**Comment by Palvehelmed** [comment]
Recently I realized that this situation will reappear when input "[[" and if the pointer happens to cover the area of the pop window for selecting a link page. I don't know if it's an issue for no-vim users. 

Clearly, when typing under Vim mode, the pointer disappears, which makes this considerably confusing when losing focus and thus the window. 

Any fix on this or reply would be highly appreciated.

**Comment by pjeby** [comment]
I was able to reproduce the issue after seeing your message, and have released a fix in 0.10.6, you should be able to upgrade and get the fix now.
