### ISSUE TITLE
Support focus shift hotkeys

### ISSUE THREAD

**Issue by Palvehelmed** [nothingislost/obsidian-hover-editor#145]
The `Focus on above` / `Focus on left` hotkeys do not work when focusing on a hover editor window.

**Comment by pjeby** [comment]
They do if there is a split in the hover editor, as far as I can tell.  Are you wanting them to navigate *out* of the hover editor and into another editor or the main window?  If that's so, you need a different command, such as one from the Cycle Through Panes plugin or the Pane Relief plugin.  The Obsidian built-in navigation functions only operate within split panes, not between separate root windows (such as hover editors and 0.15.x popouts).
