### ISSUE TITLE
 In v0.15.3, new window cannot preview "hover window" by Crtl+click

### ISSUE THREAD

**Issue by MugenLee** [nothingislost/obsidian-hover-editor#149]
like  the title, after updata to version 0.15.3, after opening a certain page in a new window, the "hover window" cannot be called up on the double chain through Crtl+click

This is very inconvenient when using KanBan, dataview and other scenarios in a new window, because Crtl+click, calling out "hover window" has become a very efficient way to use Obsidian

I don't know if it can be fixed soon

expecting the reply

thinks
@nothingislost

**Comment by pjeby** [comment]
I don't understand what you mean by "on the double chain".  Could you please provide exact steps to reproduce the problem?  Right now I don't understand where you are clicking or hovering etc.

Also, are you on the latest version of this plugin (0.10.4)?  You have to install that version using BRAT and the 0.10 releases are the only ones that work correctly with Obsidian 0.15.

**Comment by nhan000** [comment]
"on the double chain" I think they meant the chain icon ![image](https://user-images.githubusercontent.com/85216095/176422383-2d162945-adfb-448b-afc0-7c762281a723.png)

**Comment by pjeby** [comment]
> "on the double chain" I think they meant the chain icon

Ironically, that does nothing to resolve my confusion; if anything it makes things *more* confusing.  Still need steps to reproduce in any event, and confirmation the issue occurs with 0.10.4.

**Comment by MugenLee** [comment]
> 

Yes, you are right

After the OB was updated to v0.15, for some reason, Brat did not continue to update the Hover plugin, but stayed at 0.9.2

When I re-use Brat to update the Hover plugin to v0.10.4, it works fine

PS：
"on the double chain" means "bi-directional link"

My English is not very good, this passage is translated by google, please don't mind :)

**Comment by MugenLee** [comment]
> Yes, you are right
> 
> After the OB was updated to v0.15, for some reason, Brat did not continue to update the Hover plugin, but stayed at 0.9.2
> 
> When I re-use Brat to update the Hover plugin to v0.10.4, it works fine
> 
> PS： "on the double chain" means "bi-directional link" （or“two-way connections”，or "link and backlink"）
> 
> My English is not very good, this passage is translated by google, please don't mind : )

**Comment by MugenLee** [comment]
> > "on the double chain" I think they meant the chain icon
> 
> Ironically, that does nothing to resolve my confusion; if anything it makes things _more_ confusing. Still need steps to reproduce in any event, and confirmation the issue occurs with 0.10.4.

Yes, you are right

After the OB was updated to v0.15, for some reason, Brat did not continue to update the Hover plugin, but stayed at 0.9.2

When I re-use Brat to update the Hover plugin to v0.10.4, it works fine

PS：
"on the double chain" means "bi-directional link" （or“two-way connections”，or "link and backlink"）

My English is not very good, this passage is translated by google, please don't mind : )
