### ISSUE TITLE
[Bug] Popover sticks to top in fullscreen on mobile devices

### ISSUE THREAD

**Issue by decatetsu** [nothingislost/obsidian-hover-editor#152]
When I scale popover to fullscreen on my iPhone 7 Plus, it sticks on the top under the iOS bar

![image](https://user-images.githubusercontent.com/56955307/178107212-7e446479-f52a-40b3-a0f4-9c5a2a33ca7e.png)

**Comment by nothingislost** [comment]
What version of the mobile client are you running here?

**Comment by ka1tzyu** [comment]
Last one - 1.2.3 (57), API v0.14.15

**Comment by pjeby** [comment]
Please re-test with Hover Editor 0.11.7 and let us know if there is still a problem - there were some changes made to formatting of top bars and their grab settings that might improve this.
