### ISSUE TITLE
can not see the note contents of links in edit mode  if that note page has been set "move to window" in obsidian v0.15.6

### ISSUE THREAD

**Issue by Xieleilab** [nothingislost/obsidian-hover-editor#156]
can not see the note contents of links in edit mode if that note page has been set "move to window" in obsidian v0.15.6
![image](https://user-images.githubusercontent.com/78771561/178729993-bc2e29d2-50c0-4ec7-9836-f7a56359f246.png)
![image](https://user-images.githubusercontent.com/78771561/178904553-109807a5-d2e3-4405-b218-535370867fb6.png)

**Comment by pjeby** [comment]
Thanks for the report!  There is a fix out now in the 0.11.1 version of the plugin.  You will need to install it using the BRAT plugin, as this is still a beta version.  (Alternately you can download the main.js and styles.css files from [here](https://github.com/nothingislost/obsidian-hover-editor/releases/tag/0.11.1) into your vault's `.obsidian/plugins/obsidian-hover-editor` directory and restart Obsidian.
