### ISSUE TITLE
Bug with Embedded Note Titles with latest update

### ISSUE THREAD

**Issue by nhan000** [nothingislost/obsidian-hover-editor#157]
The plugin I use to generate the title is [Embedded Note Titles](https://github.com/mgmeyers/obsidian-embedded-note-titles). The title in the window is not a part of the document but was generated using the file name.

Before latest Hover Editor update
![image](https://user-images.githubusercontent.com/85216095/179219339-321e0bc4-ca0a-4d94-9d92-6df0d68a8b20.png)

After latest update Hover Editor the title displaces the text body to the right
![image](https://user-images.githubusercontent.com/85216095/179219446-763e4167-9a70-4ee8-b536-abbd01a7ab1c.png)

**Edit**: As I reverted to previous Hover editor version (0.10.7) the title isn't rendered at all, _which I think is better because it saves space in the Hover preview and the title is already displayed in the title bar._
![image](https://user-images.githubusercontent.com/85216095/179226739-395958c7-edbc-4760-b6bf-45620c7a4dd3.png)

**Comment by nhan000** [comment]
Same issue happens with hover preview triggered from the [Quick Explorer](https://github.com/pjeby/quick-explorer) plugin 
![image](https://user-images.githubusercontent.com/85216095/179223181-66e10c35-841a-4487-b560-15c0732c332e.png)

However, in another vault it display correctly
![image](https://user-images.githubusercontent.com/85216095/179223389-ebe720ff-ab98-4673-808d-bebe946ee452.png)

All plugin were updated using the "check for updates" in Settings.

**Comment by pjeby** [comment]
I'm not able to reproduce this with the latest version of Obsidian, the plugins in question, and the default theme.  Can you list your specific versions of everything?

**Comment by nhan000** [comment]
There's an update by the Embedded Note Titles plugin 4 hours before your comment and the issue has been fixed. Thanks a lot!
