### ISSUE TITLE
Conflict with Maximise Active Pane plugin

### ISSUE THREAD

**Issue by Sriramgireesh** [nothingislost/obsidian-hover-editor#159]
When "maximise active pane" is toggled, the hover editor flickers and immediately disappears.

**Comment by pjeby** [comment]
The Maximize Active Pane plugin appears to be unmaintained (not updated in a year and a half) with many outstanding bugs.  I would suggest using the Pane Relief plugin instead: it has a maximize command that supports both hover editors and popout windows (Obsidian 0.15.6 and up).
