### ISSUE TITLE
Bug - Keeping focus

### ISSUE THREAD

**Issue by transmitthis** [nothingislost/obsidian-hover-editor#160]
V 0.112
Win 10

To Repeat:
Have Obsidian open. Focus on another program, Chrome for example.
Move mouse over a hover link in Obsidian, then back to Chrome.

Result: 
Hover window will act as expected, opening and closing on hover - all is good, 
However In Taskbar Obsidian Icon will Flash constantly until focus is given back to Obsidian (Clicking anywhere on program)

Why it's an issue.
You could be using Obsidian as reference, browsing the web, and very often you would find the flashing or highlighted Icon in the taskbar distracting you.

Importance: 
Minor
If you are in a bug fix mood, maybe you could have a look.

Fixed by:
Disabling Hover plugin. / auto hiding taskbar, gouging eyes out, or constantly clicking on Obsidian  :)

**Comment by pjeby** [comment]
Have you tried turning off Auto Focus in the Hover Editor settings?

**Comment by pjeby** [comment]
I was able to reproduce the issue; there were some API changes in Obsidian 0.15.6+ that affected focus; please let me know if the problem persists after you update to 0.11.3.

**Comment by transmitthis** [comment]
Sorry Pjeby, Gmails spam filter ate your notifications, and I only just checked on this.

Yes the problem still persists with 0.11.4

No I haven't tried [Turning off Auto Focus] - Yes this does resolve issue. and it's fine for me - thanks
