### ISSUE TITLE
Hover Editor - Bug Involving Links Inside Kanban Plugin Cards

### ISSUE THREAD

**Issue by julroger2013** [nothingislost/obsidian-hover-editor#161]
This is an incredibly niche bug — and I'm not sure whether it's attributable to Hover Editor or mgmeyers' Kanban plugin—but the following occurs: 

WHEN

- A note is in Kanban mode
- One of the cards on the Kanban note includes a note/header/block link
- The user ctrl/cmd + clicks the link inside the card

THEN

The note/header/block link opens not in a new workspace pane, as might be expected, but instead in a split view within the Hover Editor popup that normally occurs when hovering over the link. 

This occurs only when the note is in Kanban mode. If the note is set to markdown mode using the Kanban plugin's: "Toggle between Kanban and markdown mode" command, then the note opens exactly as might be expected—inside a new pane in the workspace.

**Comment by pjeby** [comment]
So, I did some investigation, and it appears the issue is that Kanban is capturing the mouse events that Hover Editor would use to know that you've clicked away from the editor.  I've implemented a workaround that is now available in 0.11.4.
