### ISSUE TITLE
Naming the wrong file

### ISSUE THREAD

**Issue by DEabcdp** [nothingislost/obsidian-hover-editor#167]
There is a bug, it seems, mouse over file A in the file list, press the shortcut key to create a new file B, then the background will automatically create a new hover window on A (guessing that the focus is moved to file A).

Because I built a template command on Tempelater, the new file will automatically pop up and assign the file name to file B. But because Hover gave the focus to A, the named file name will be automatically assigned to A instead of B.

Then the version history of file A can't be found, because A was renamed, if you can't remember what A was called...

<img width="319" alt="image" src="https://user-images.githubusercontent.com/62452364/183805754-5e68df8d-964c-41c2-b81d-453eb3e5a5e5.png">

<img width="727" alt="image" src="https://user-images.githubusercontent.com/62452364/183806970-bef8a357-75f2-45d9-ac07-29fb8950bbab.png">

↑The focus on the graph is on file B. This is because the new file I created is at the bottom of the list. You can see that file A has been moved down. But if you create a new one in the top folder, the focus will be on file A (the naming of whichever file the cursor is next in will rename the file). Here is just a demonstration.

<img width="691" alt="image" src="https://user-images.githubusercontent.com/62452364/183807059-d4ecc77c-231a-42fa-a7e5-3f7e9d9ee1c7.png">

<img width="250" alt="image" src="https://user-images.githubusercontent.com/62452364/183807252-6cfe67a5-7d52-4163-98af-e24013199503.png">

**Comment by pjeby** [comment]
If I understand you correctly, this is not a bug but Hover Editor doing as it is designed and configured to do.  If you don't want new popovers to be focused, you need to turn off the "auto focus" option in hover editor settings.

Alternatively, if you change the hotkey you use for this operation to not include the Control key (or Command key on Mac), then it will not trigger a popup at all.

**Comment by DEabcdp** [comment]
> If I understand you correctly, this is not a bug but Hover Editor doing as it is designed and configured to do. If you don't want new popovers to be focused, you need to turn off the "auto focus" option in hover editor settings.
> 
> Alternatively, if you change the hotkey you use for this operation to not include the Control key (or Command key on Mac), then it will not trigger a popup at all.

I tried as you said, no effect, as long as I open Hover Editor, this problem will always exist, and vice versa is normal.
1. In Obsidian's own option of hover preview which requires holding down Command key, if you uncheck the file list, then it will automatically generate a new preview window when the mouse moves over the file; and you have to hold down Command key when this option is checked. Also, I don't get misnamed when I turn off the Hover Editor plugin, whether I turn this option on or off.

2. After turning on Hover Editor (which takes over Obsidian's own preview window), whether I turn on "auto focus" or not, as long as I put the mouse focus on all but the first file (the list moves down one line when a new file is created) and press Command+N, the problem is reproduced.

My speculation is that the Command in the new file shortcut (Command+N) triggers Obsidian's own preview window by mistake (but this does not cause the error, see point 1), and even if the Hover Editor's focus is not on this preview window, my templater naming command assigns the name to the new window instead of the window where the focus is .

I have put my template below, which may not be relevant to this project and which you can ignore as the author. I'm working on this problem.

<%*
let title = tp.file.title;
if (title.includes("untitled")) {
 title = await tp.system.prompt("Please enter the name of the file to be created", title);
  if (!title) return;
}
if (title == ""){
 title = "untitled";
} else {
 await tp.file.rename(title);
}
-%>

**Comment by pjeby** [comment]
Is the file explorer the active pane?  And does the hovered pane become active?

From my reading of the code, it would appear that templater's notion of the "active file" would only point to the hovered file if the hovered pane became active/focused (however briefly), *and* the active pane was not a navigable file view at the time the command was triggered.  If the hovered file did not become active via autofocus, templater should see the most recently-active file view as the active file instead.

Even so, however, the `tp.file.title` and `tp.file.rename` should be targeting the *target* file, not the active file, and there doesn't seem to be a way that Hover Editor could affect the target file, since it is set when the new file is created.  (I'm assuming here that your template is set to run when a new file is created.)

**Comment by DEabcdp** [comment]
> Is the file explorer the active pane? And does the hovered pane become active?
> 
> From my reading of the code, it would appear that templater's notion of the "active file" would only point to the hovered file if the hovered pane became active/focused (however briefly), _and_ the active pane was not a navigable file view at the time the command was triggered. If the hovered file did not become active via autofocus, templater should see the most recently-active file view as the active file instead.
> 
> Even so, however, the `tp.file.title` and `tp.file.rename` should be targeting the _target_ file, not the active file, and there doesn't seem to be a way that Hover Editor could affect the target file, since it is set when the new file is created. (I'm assuming here that your template is set to run when a new file is created.)

The file explorer is not the active panel, I just move the mouse over the second file but don't click on it.

The hover window is also not the active panel (whether Auto Focus is on or not) because I tried with the arrow keys after typing the file name and the input cursor was on the new file (but the naming was still on the file in the hover panel), and pressing Command+W closed the panel of the new file instead of the hover panel.

**Comment by DEabcdp** [comment]
It should be the problem of template.
