### ISSUE TITLE
After updating to version 0.16.0, opening HOVER plugin will cause the mouse hover preview function to fail; and opening hover hover box can only be a very small height preview box, can not adjust the height of the preview box.

### ISSUE THREAD

**Issue by MILKMILKKING** [nothingislost/obsidian-hover-editor#169]
The hover preview feature is very important and we suggest fixing it as soon as possible.

**Comment by pjeby** [comment]
It works fine for me on 0.16 using the default theme.  Most likely you have a theme or snippet conflict.  Try using the default theme and disabling snippets.

**Comment by MILKMILKKING** [comment]
Thanks for your help, the Hover plugin is back to normal!
