### ISSUE TITLE
FR: Support popovers on standard markdown links such as [example](link)

### ISSUE THREAD

**Issue by Castleeee** [nothingislost/obsidian-hover-editor#17]
support [a](./a.md)，and when draging or resizing window ，the content become blured.

![Kapture 2022-03-12 at 16 29 48](https://user-images.githubusercontent.com/33923279/158010487-8f8ec66a-407f-4934-9087-b0b4864bd806.gif)

**Comment by Castleeee** [comment]
![Uploading 图片.png…]()

**Comment by Castleeee** [comment]
![图片](https://user-images.githubusercontent.com/33923279/158010518-043387c7-5b74-40fe-acf2-4b3c74a55343.png)

**Comment by liu528** [comment]
![image](https://user-images.githubusercontent.com/69421063/158022904-7ee1ff57-7f9f-463f-ab80-ef2de0672b8b.png)
![image](https://user-images.githubusercontent.com/69421063/158022913-2a09e386-aa5c-4138-b536-a04f5fc30424.png)

**Comment by liu528** [comment]
you see, the first wiki link can work, while the second standard md link can't work.
Will it be solved? Because I think your plugin may be made based on the core plugin, which doesn't support the standard md link.
I love your plugin and I hope it will be better, so I think it can be solved.

**Comment by nothingislost** [comment]
I'll look into supporting hover on standard markdown links. For now, you can open them by right clicking the standard markdown link and choosing "open in new popover" from the context menu.

**Comment by nothingislost** [comment]
This will be supported in the next Obsidian insider release, 0.14.1

**Comment by nothingislost** [comment]
This is officially supported by Obsidian in the latest insider release
