### ISSUE TITLE
No editing in the hover window since 0.16

### ISSUE THREAD

**Issue by DutchPete** [nothingislost/obsidian-hover-editor#171]
The hover editor used to have an icon for toggling Reading/Edit mode, but no longer.
The HE open in Reading mode and I don't see a way to edit the text within the HE p[op-up window.

**Comment by pjeby** [comment]
In Settings > Appearance > Advanced, turn on "Show tab title bar" to get back the view header from previous Obsidian versions.

**Comment by DutchPete** [comment]
You obviously did not read my issue correctly. I did not ask about the view header!

Nevertheless, I tried your suggestion to see if it would solve my issue, alas it did NOT.

So, please reopen this issue. Thank you.

BTW, have you taken over this plug-in from @nothingislost ? I noticed you have answered in a number of issues in the list. I'm just curious.

**Comment by pjeby** [comment]
For me, the view header is where the reading / editing icon appears - directly to the left of the three-dots "more" menu.  This icon is supplied by Obsidian, not Hover Editor, so if it is not appearing when you have the view header turned on, this is an issue with Obsidian.  Are you using 0.16.2?  I seem to recall an early alpha of 0.16 not having the icon, and there being complaints about it, but I am not sure my recollection is accurate.  I am using 0.16.2 and it appears in all panes with the view header visible.

If you are seeing it on other panes but not in the Hover Editor, then make sure you are showing the view header *in* the hover editor.  If you aren't seeing it on other panes, then it is an Obsidian issue.

**Comment by DutchPete** [comment]
OK, I got it. I had disabled *Show tab title bar*. Enabling it showed it.

When the pop-over opens, it is in Reading mode. Is it possible to have LP as the default mode? Should I open a new issue for that?

**Comment by pjeby** [comment]
In Hover Editor settings, the first setting controls whether hover editors will open in reading mode, editing mode, or match the current view.

**Comment by DutchPete** [comment]
Yep, that works. My apologies, somehow I had not seen it.
Thank you. The issue can be closed.
