### ISSUE TITLE
[Feature request] New note in popover

### ISSUE THREAD

**Issue by jsmorabito** [nothingislost/obsidian-hover-editor#177]
Would be cool to have a command that opens a popover window for a new note:

![image](https://user-images.githubusercontent.com/46250921/190244464-170f1e0a-19c0-4cdc-91c8-3cfb3c738a02.png)

**Comment by pjeby** [comment]
You can create a command like this using the QuickAdd plugin's macro feature: see issue #175 for detailed instructions on how to create a similar command, just replacing the "open daily note" command with "new note".

**Comment by jsmorabito** [comment]
@pjeby Thanks for the heads up! I got tripped up on this step: "Click the gear first, and pick the macro you created from the dropdown, then exit that dialog and click the lightning bolt. It will turn yellow to show your command is enabled." as I didn't see a dropdown menu to select the macro.

I did, however, remember that phibr0 has a [macros plugin](https://github.com/phibr0/obsidian-macros) which did exactly what I needed!
