### ISSUE TITLE
[Feature Request] Map ESC to close currently focused HE window 

### ISSUE THREAD

**Issue by gala8y** [nothingislost/obsidian-hover-editor#179]
Thx for developing HE. 

FR: Map ESC to close currently focused hover editor window.

Rationale: It's easier to focus window with mouse and close it with ESC key than closing it by clicking x in the window bar.

**Comment by pjeby** [comment]
If the hover editor window is focused, you can use the standard Obsidian "close pane" command (or "close tab" in Obsidian 0.16).  The default shortcut is Ctrl-W (or Cmd-W on Mac).

**Comment by gala8y** [comment]
Yeah, thanks for the answer. I just realized this right after posting. Users... :)
