### ISSUE TITLE
Bug: Cannot hover multiple notes in graph view

### ISSUE THREAD

**Issue by HEmile** [nothingislost/obsidian-hover-editor#18]
See video. This also happens for Juggl.

https://user-images.githubusercontent.com/1289165/158018739-c95d5e09-2670-475a-b903-babf25a75674.mov

 I think this is probably because the hover management is done by Obsidian when using the hover-link trigger.

**Comment by nothingislost** [comment]
Yeah, I'm aware of this one. Still need to sort out the best way to allow for this without breaking other stuff.

**Comment by Obadiahcruz** [comment]
would this help the unresolved links in the graph view? as of now you cant hover over links that are not notes yet in the graph view

**Comment by nothingislost** [comment]
https://github.com/nothingislost/obsidian-hover-editor/releases/tag/0.3.6 resolves this and also allows for popovers on unresolved graph nodes

**Comment by Obadiahcruz** [comment]
this is amazing
