### ISSUE TITLE
Bug: Hover Editors docked to workspace do not support tabs

### ISSUE THREAD

**Issue by leoccyao** [nothingislost/obsidian-hover-editor#184]
Steps to reproduce:
1. Open a new hover editor
![Vault with a new tab and a new tab in a hover editor](https://user-images.githubusercontent.com/45076643/197363250-8aaddeea-d553-4f20-8f5c-602a2e985e16.png)`
2. Dock the hover editor to workspace via the command
![Vault with two panes, a new tab on the left and a docked hover editor on the right](https://user-images.githubusercontent.com/45076643/197363273-db4bfca4-60e7-4e81-a4db-982e7c4140ab.png)
Notice already the difference in appearance between the two panes. Briefly looking at the element tree, the left pane is a `<div class="workspace-tabs">` (which contains `<div class="workspace-tab-container">`, which contains `<div class="workspace-leaf">`), while the right pane is a `<div class="workspace-leaf">`.
3. Try to create a new tab
Expected: new tab is created in the pane that was just docked
Result: command checking fails (hotkey does nothing, command does not show up in command palette)
![command palette with "new tab" typed, but the new tab command missing](https://user-images.githubusercontent.com/45076643/197363372-258ec30e-7e9b-4921-b8be-bfdc6e945944.png)

Windows 10, Obsidian v1.0.0, Hover Editor v0.11.6. Same result on iPadOS 15.7, Obsidian Mobile v1.4.0, Hover Editor v0.11.6.

**Comment by pjeby** [comment]
The dock command doesn't work properly for 0.16/1.0 yet.

To work around it, display the view header of the hover editor, and then drag the icon into the workspace and drop it in an existing tab group.

Docking should be fixed when 0.11.7 is released

**Comment by pjeby** [comment]
This should now be fixed in 0.11.7.
