### ISSUE TITLE
[BUG] Hover editor scrolls to the bottom of the previewed file

### ISSUE THREAD

**Issue by Lulullia** [nothingislost/obsidian-hover-editor#186]
Hi! Love this plugin, it really removes a lot of friction.

But recently I have been experiencing a strange behavior: when hovering over a link (from anywhere) the hover editor appears as expected, but scrolls to the bottom of the content (if the note is long enough).

What Hover Editor shows -- bottom of the note
![image](https://user-images.githubusercontent.com/47358820/198887067-c72ba66e-2a46-4413-bf24-aa531a3d4719.png)

Hover Editor disabled, normal preview -- top of the note as expected
![image](https://user-images.githubusercontent.com/47358820/198887093-ec287259-588b-4116-816e-3eee164ae2d1.png)

I tried changing settings and disabling other plugins, but the issue persists.

**Comment by pjeby** [comment]
Can you reproduce in the sandbox with stock theme, no snippets, and only the Hover Editor plugin installed?

**Comment by pjeby** [comment]
Ok, it's definitely an Obsidian 1.0.x issue, as it does not repro in 0.15.9.  It will take some (perhaps considerable) investigation as to what's going on.

The problem also doesn't occur unless editing mode is used; unfortunately using reading mode and then switching to edit mode has the same effect.  So definitely some digging to do to figure this one out.

**Comment by pjeby** [comment]
This should now be fixed in 0.11.7.
