### ISSUE TITLE
Support previewing footnotes

### ISSUE THREAD

**Issue by b0o** [nothingislost/obsidian-hover-editor#187]
It would be awesome to be able to preview footnotes without clicking on them.

**Comment by AhmadFCheema** [comment]
See plugin [Better footnote](https://github.com/aidenlx/better-fn). This turns footnotes into convenient pop-ups.

Note that, by default, the normal footnotes display at the bottom gets hidden with this plugin. This can be changed in the plugin settings.

**Comment by Comprehensive-Jason** [comment]
I think Hover Editor now works on footnotes too. See here:

https://github.com/nothingislost/obsidian-hover-editor/assets/68677082/7db56738-b038-4301-b7be-61742c4b022c

**Comment by j-adel** [comment]
It doesn't work for me, it just points to the top of the page. It actually ruins the new 1.6 feature of footnotes preview as well. Is there a way to disable it for footnotes?

**Comment by pjeby** [comment]
Not at the moment, no.  When I have some time I plan to see whether there's a way to not have hover editor be all-or-nothing with respect to the built-in previews, so we could e.g. let footnotes pass through.  (And also perhaps turn previews into full editors with a hotkey, which is another outstanding feature request.)

(Not sure when that will be, though; I'm still personally on 1.5 and don't expect that to change very soon.)

**Comment by pjeby** [comment]
I've just released 0.11.21 of Hover Editor, which has toggles you can use to disable footnotes and other "part of a document" links from being handled by Hover Editor.  (And it defaults to off for Obsidian 1.6 and above.)  So if you want to use the new built-in preview instead of HE's, you're good to go.

For HE *doing* the previewing, I can't repro the problem @j-adel  is seeing.  I'm currently using the below text as a test on 1.7:

```markdown
Here's a simple footnote,[^1] and here's a longer one.[^bignote]

[^1]: This is the first footnote.

[^bignote]: Here's one with multiple paragraphs and code.

    Indent paragraphs to include them in the footnote.

    `{ my code }`

    Add as many paragraphs as you like.
```

And Hover Editor displays both links just fine, despite this being at the bottom of a much bigger note.  It also correctly highlights the targeted footnote if the opened editor is in source mode.  Can you (@j-adel) provide the text that is not working?  Thanks.

**Comment by j-adel** [comment]
I believe it wasn't working for me because the footnotes weren't at the bottom of the file. Here's an example in which HE fails to show the footnote while Obsidian Page Preview doesn't:
```
Here's a simple footnote,[^1] and here's a longer one.[^bignote]

[^1]: This is the first footnote.

[^bignote]: Here's one with multiple paragraphs and code.

    Indent paragraphs to include them in the footnote.

    `{ my code }`

    Add as many paragraphs as you like.

This is text.
This is text.
This is text.
This is text.
This is text.
This is text.
This is text.
This is text.
This is text.
This is text.
This is text.
This is text.
This is text.
```

**Comment by pjeby** [comment]
Do you have Hover Editor configured to show Reading Mode or Editing mode?  (It works for me in Editing Mode.)

**Comment by j-adel** [comment]
That was with a Sandbox vault. To be clear, the popup does show, it just doesn't scroll properly to the footnote, instead it shows the "this is text." part

**Comment by pjeby** [comment]
I'm not able to reproduce the scrolling issue, even in reading mode.  It scrolls and highlights in editing mode, however, and of course now you have the option to turn it off for footnotes, blocks, or even subheads if you prefer.

**Comment by j-adel** [comment]
![image](https://github.com/user-attachments/assets/a7cc6a46-241a-4dd8-ac9b-32665ef66822)
Here it is in a Sandbox mode as I've described before.

**Comment by pjeby** [comment]
Yes, I'm aware.  There is some sort of scroll targeting issue that some people have with *any* location besides the top in Hover Editor (in reading mode) that I have never been able to reliably reproduce without *very* large notes.  The large note issue is actually in Obsidian itself, as I *have* been able to repro it with large enough files and sent samples to the Obsidian devs back in February: https://forum.obsidian.md/t/opening-new-tab-in-reading-mode-via-heading-or-block-link-takes-multiple-seconds/77208

(I don't know if that's *actually* the same problem or not; it's just the closest thing to the problem I've ever been able to reproduce.)
