### ISSUE TITLE
[Bug]: Initial popover height can't be set as percentage

### ISSUE THREAD

**Issue by hustrjh** [nothingislost/obsidian-hover-editor#190]
Can't `Initial popover height` be set as percentage? When I set  `Initial popover height` to be `50%`, the popover window looks like picture below. However `Initial popover width` functions normally in percentage. I remember that the setting works normally until `Obsidian` updates to maybe 0.15.9.
![image](https://user-images.githubusercontent.com/69783980/201025237-a7800324-d5c7-4024-9d5c-f7cee7885800.png)

**Comment by pjeby** [comment]
There was a problem with various calculations assuming the height was expressed in px, rather than % or vh or calc or anything of that sort. It should be fixed in 0.11.8.

**Comment by hustrjh** [comment]
@pjeby Thank you for your quick reply. :+1:  Now `hover editor` works well. But I'm still a little curious about the reason why 100% height is not as high as the window. So as the width.

**Comment by pjeby** [comment]
Currently, hover editors have a maximum size of two-thirds of the window size (horizontally and vertically), except when maximized.

**Comment by hustrjh** [comment]
Thank you for your patient answer. :heart:
