### ISSUE TITLE
Can't resize the height of the editor

### ISSUE THREAD

**Issue by dcoales** [nothingislost/obsidian-hover-editor#194]
Hi,

I'm running 0.11.8 of hover editor and whenever I try to resize the height of the editor it won't go beyond the initial size set in the settings.  It's as though it's now using the initial size as the maximum size.

Thanks,
David

**Comment by pjeby** [comment]
I can't repro this - does it do it with stock theme and all CSS snippets turned off?  If so, does it do it with other plugins off?

**Comment by dcoales** [comment]
Good points.  I should have checked that first.  I will check now.

**Comment by dcoales** [comment]
My apologies.  With default theme and all other plugins disabled the issue goes away.  I will now start the hunt for the guilty party.  Sorry to bother you.

**Comment by dcoales** [comment]
Okay, the guilty party is the Things theme (in case you were wondering).

**Comment by pjeby** [comment]
You should let them know.  They have a `max-height` of `40vh` set, and it's at a priority where it's overriding Hover Editor's `unset` max height.  So you can't make it any bigger than 40% of the screen height.
