### ISSUE TITLE
Dead empty space at the end of a note

### ISSUE THREAD

**Issue by Missionary2112** [nothingislost/obsidian-hover-editor#198]
## Issue
When I scroll all the way down in Hover window, it allows me to scroll way pass the bottom of the note, creating dead empty space. 
I would like it to stop right where it should be. 

### Hover Mode
![2023-01-20_02 37 37_CSX|400](https://user-images.githubusercontent.com/98799613/213675629-dfc76a77-4a84-42ef-8b3b-0913a2eb587d.jpg)

### Normal Preview
![2023-01-20_02 49 51_CSX](https://user-images.githubusercontent.com/98799613/213677817-d065d302-8a62-43f2-8415-6a7c4a356aef.jpg)

**Comment by pjeby** [comment]
I'm not able to reproduce this.  More specifically, I can't reproduce the normal preview **not** having a half-screen of blank space at the end of every note.  As far as I'm aware, Obsidian *always* has extra space at the bottom of notes, in editing or preview mode - I have never known it not to, on any version that I can recall.

Can you upload the exact note text with the issue?  Specifically, a note that does NOT have extra space shown in the preview, when used with the stock theme in the Obsidian sandbox with no plugins or snippets active?

**Comment by Missionary2112** [comment]
So this is the default theme from Obsidian
- **The preview window**
![2023-02-02_13 18 15_CSX](https://user-images.githubusercontent.com/98799613/216451847-ba2a734f-595a-4201-8e61-0776640e461e.jpg)

- **The text content from the note**
![2023-02-02_13 17 01_CSX](https://user-images.githubusercontent.com/98799613/216451909-b74091bf-0450-4180-9528-96c5a4c3580e.jpg)

I actually can reproduce what you said that Obsidian always has extra space at the bottom of notes, especially when I'm using "Hover Editor" plugin. 

- **Preview window when Hover Editor is enable**
![2023-02-02_13 20 49_CSX](https://user-images.githubusercontent.com/98799613/216452282-1a572045-2c8e-46d8-9b8c-2eaef07ad6da.jpg)

**Comment by pjeby** [comment]
Please upload the *file* that produces the problem, not a picture of the file.  Thanks.

**Comment by Missionary2112** [comment]
[Reading minds through body language.md](https://github.com/nothingislost/obsidian-hover-editor/files/10575619/Reading.minds.through.body.language.md)

**Comment by pjeby** [comment]
So, I'm not able to get any reading or preview view that *doesn't* have whitespace below that, on Obsidian 0.15.9 or 1.1.10, with or without plugins, stock theme, etc.  Even without Hover Editor.

**Comment by Missionary2112** [comment]
It's weird. Anyway, thank you for checking that out.
