### ISSUE TITLE
Drag of link should discard initial popup hovered by that link

### ISSUE THREAD

**Issue by pjeby** [nothingislost/obsidian-hover-editor#20]
Right now if I try to drag a link from a source that doesn't require ctrl to hover, the popover appears during the drag and obscures the underlying (main) editor pane that I'm trying to drag *to*.  Probably watching for a dragstart event on the element that triggered the hover-link event would allow detecting that as a case to ditch the initial popover.

**Comment by pjeby** [comment]
An additional note: this could probably be done by checking for a mousedown outside the popup, since either a click or drag outside an unpinned popup should close it.

**Comment by nothingislost** [comment]
Hmm, I already have a mousedown handler doing this but you have to click before the trigger delay (200ms by default but customizable in settings). Where are you seeing this happen specifically?

I suppose I could make the click handler auto hide the popover if a click is detected within a certain amount of time to make it even less likely to accidentally show a popover.

**Comment by pjeby** [comment]
What I'm seeing happen is: I try to drag a link from a source that doesn't require the ctrl key to hover.  No matter how quickly I attempt to drag, the popup shows up and doesn't go away until I finish or cancel the drag, because mouseover, mouseenter, etc. events don't fire during drag-drop: only dragover, dragenter, etc.  So the popover hangs around because it doesn't see a mouseover until after the drag is finished.

In any event, it seems to me that if a popup isn't pinned and you mousedown anywhere outside of it, it should always go away, no matter how long it's been since you began the hover.  If you need to drag something *into* the popover, you can always pin it first (or turn on auto-pinning), but if you're dragging something elsewhere, there is no way to get the popover out of the way.

(To be fair, I have checked and it appears Obsidian's builtin popovers actually have this same problem...  but then this would just be another way this plugin is superior to the builtin popovers.  :wink:)

**Comment by nothingislost** [comment]
Hmmm, yeah, that's fair. I suppose I can keep the abort click handler around for the life of the popover... or until it gets pinned.

If you're seeing this on QE then part of the problem is that my existing click handler is on the popover targetEl which I don't believe you're setting... so it doesn't even try to do the logic I was talking about above. I can switch the handler to being on the document body though to solve the targetless popover issue.

**Comment by pjeby** [comment]
No, I hadn't actually tried it from QE, this was just dragging a link from one markdown view (in reading mode) to another (in editing mode).  But that sounds like a good idea.

As far as I know, the target element is indeed optional by design in Obsidian core: Obsidian checks on all code paths that it is a truthy value before using it for any dom stuff.  The reason QE omits it is because otherwise the popovers close immediately when you are using the keyboard.  (As the mouse is not necessarily on the targetEl when triggered.)

I see you've implemented this in 0.3.5, so I will close this.
