### ISSUE TITLE
Hover Editor does not hide banner in Preview window

### ISSUE THREAD

**Issue by Missionary2112** [nothingislost/obsidian-hover-editor#205]
I just contacted to Banners plugin and realize that Hover Editor does not hide banner in Preview window despite `Show banner in preview embed` being turned off.

**Comment by pjeby** [comment]
Presumably that setting is intended for embeds and the built-in page preview.  Hover Editors aren't a page preview or embed, they're a regular tab that just happens to be hovering.  If you want to disable banners in hover editors, you'll need the Banners plugin to add another option for that, or else write some custom CSS to do it yourself.

**Comment by Missionary2112** [comment]
I'll contact Banner author. Thanks.
