### ISSUE TITLE
Suggestion: Popout and dock

### ISSUE THREAD

**Issue by ProStashio** [nothingislost/obsidian-hover-editor#215]
I've had a little play around with this and love it!

Buggest things I found myself wanting is the ability to popout the windows and to be able to dock them to the tabs if I decide I want to spend more time on the note and have more screen space for it

**Comment by pjeby** [comment]
To do those things, you need the hover editor's view header to be visible.  You can click the little box with a `v` in it (in the hover editor's title bar) to show it, or you can set it to be visible by default in the Hover Editor settings.

Once the header is visible, all the operations you want are available via the icon on the left of the header, and the three-dots menu on the right.  Dragging the icon will let you dock the pane as a tab, or drop it on the workspace to pop it out as a window.  The menu also has options to dock or to pop it out.

To turn a tab into a hover editor, right-click it and select "Convert to Hover Editor".  (If the tab is the only tab in a popout window, drag it to another window first or the window will close and you will lose the tab.)
