### ISSUE TITLE
background-color in dark mod

### ISSUE THREAD

**Issue by kin30528** [nothingislost/obsidian-hover-editor#216]
The deep grey background-color in dark mode will be nice, I currently use css to change the color of the background 😊

# before
![image](https://github.com/nothingislost/obsidian-hover-editor/assets/121107652/4146b173-9e92-4c4b-b213-83e2cd7fcb64)

# after
<img width="960" alt="image" src="https://github.com/nothingislost/obsidian-hover-editor/assets/121107652/cef75b0b-7bea-40bc-9c22-a6eacccfc8d2">

**Comment by pjeby** [comment]
I'm confused - there doesn't seem to be a hover editor in that picture that I can see?  How does this relate to the Hover Editor plugin?

**Comment by kin30528** [comment]
omg....my article was posted on the wrong plug-in website🤣🤣🤣
