### ISSUE TITLE
Plugin is not triggered anymore after update

### ISSUE THREAD

**Issue by mafsi** [nothingislost/obsidian-hover-editor#217]
Theme: Minimal, Obsidian: 1.3.1, Installer Version 1.2.8. Arch Linux, All stufs enabled in Page View, and Plugin Hover Editor

**Comment by mafsi** [comment]
By trigger I mean that when I hover over a link there is no pop'up window as before. Right clicking shows Open in hover editor and is working. The idea is that to get the pop up window the moment I hover the cursor on a link.

**Comment by pjeby** [comment]
Does it work when you hold Ctrl down?

Earlier you mentioned that "All stufs enabled in Page View" -- if by that you mean you turned on all the toggles in Obsidian's "Page Preview" settings, then please note that turning the toggles on means (as it says in the title) "**Require Ctrl** to trigger page preview on hover".  If you want them to appear without holding Ctrl, you need to turn the toggles in that settings page *off*.

**Comment by mafsi** [comment]
Maybe I didn't make myself understood, since English is not my native language.
CTRL+Click shows a pop-up of the link, but it belongs to the Page View plugin. Right-click on a link, it shows me Open in Hover editor and it works.
What I remember (I haven't used Obsidinan for a while), that before introducing PageView Hover Editor takes over the task and shows the window. That way I could stick it to the edges. Now I have to right-click to open the link in Hover Editor. I don't want this. I want that, when I hover the mouse over a link, to automatically open the Hover Editor window. That's the way it used to be, as far as I remember.

I tried to disable PageView and leave only Hover Editor active, thinking that this way Hover Editor would take over. This does not happen. If I activate the official PageView plugin, it opens a window that is PageView, not Hover Editor. To open the window in Hover Editor, I have to right-click. Is this new Hover Editor functionality after introducing the official PageView plugin, or are some settings wrong with me?

Thank you very much for your kind answer.

**Comment by pjeby** [comment]
You need to have both plugins active.  Ctrl while moving the mouse onto a link should pop up a hover editor.

What links are you hovering on?  Links in a note?  Or something else?

**Comment by mafsi** [comment]
> What links are you hovering on? Links in a note? Or something else?

Internal links. I solved the problem. I uninstalled the Hover Editor and reinstall it. Is working now! Thanks a lot for the patience!
