### ISSUE TITLE
Conflict with Force note view mode plugin

### ISSUE THREAD

**Issue by ProudBenzene** [nothingislost/obsidian-hover-editor#220]
Thank you for your fantastic plugin! It really helps me a lot especially when I am learning English! But I've found some false when I was using the plugin with the force note view mode plugin.

![iShot_2023-06-07_11 56 39](https://github.com/nothingislost/obsidian-hover-editor/assets/93238080/8bb2bc2b-2a82-4d02-953b-dabba4993680)

Like the gif shows, this is in a sand box, and although I've toggled the Reading View in the plugin settings, notes will turn into the editor mode automatically.

And if I turn off the force note view mode plugin, the false disappears.

**Comment by pjeby** [comment]
As far as I can tell from your video, both plugins are working as designed.  Hover Editor opens the window in Reading View as requested, and then when the pane receives focus the other plugin switches it to edit mode.

If you want to be able to show things in preview until such time as you actually click on them, you probably want to turn off "Auto Focus" in the Hover Editor settings.  Then the Force View plugin will not change the view mode until you click in the hover editor or otherwise make it active.

**Comment by ProudBenzene** [comment]
> 

In fact, if you don't add `obsidianUIMode: preview` to the notes' metadata, like the notes in my demo(only `alias` in metadata), the force note view mode plugin won't work at all.

And I tried the way you mentioned above. I turned off the `auto focus new tabs` in the settings, but it didn't really work.

**Comment by pjeby** [comment]
"Auto focus new tabs" is not what I said.  I said ""Auto focus" in the Hover Editor Settings", which is different.

Second, in the video above, you have the "Ignore force view when not in frontmatter" setting turned off in the Force View settings.  With that off, the Force View plugin changes every view to reading mode as soon as you switch to that pane or tab.

By having those both of those settings the way you have them in the video, it will produce this result.  If you turn off what I said before to turn off, OR you turn *on* the "Ignore force view when not in frontmatter", then the problem will not happen.

**Comment by ProudBenzene** [comment]
> "Auto focus new tabs" is not what I said. I said ""Auto focus" in the Hover Editor Settings", which is different.“自动对焦新标签”不是我说的。我在悬停编辑器设置中说了“自动对焦”，这是不同的。
> 
> Second, in the video above, you have the "Ignore force view when not in frontmatter" setting turned off in the Force View settings. With that off, the Force View plugin changes every view to reading mode as soon as you switch to that pane or tab.其次，在上面的视频中，您在 Force View 设置中关闭了“Ignore force view when not in frontmatter”设置。关闭后，Force View 插件会在您切换到该窗格或选项卡时立即将每个视图更改为阅读模式。
> 
> By having those both of those settings the way you have them in the video, it will produce this result. If you turn off what I said before to turn off, OR you turn _on_ the "Ignore force view when not in frontmatter", then the problem will not happen.通过将这两种设置都按照视频中的方式进行设置，将产生此结果。如果你把我之前说的关掉，或者你把“Ignore force view when not in frontmatter”打开，那么问题就不会发生了。

Thank you very much! The problem is solved perfectly and it helps me a lot!🥰
