### ISSUE TITLE
Can we please get an option to turn on to only see header content when linking to a header?

### ISSUE THREAD

**Issue by Eneswar** [nothingislost/obsidian-hover-editor#223]
In vanilla Obsidian when you link to a header in a note, it will only show you the header and the things under it, but when I use hover editor, which I want to continue to use, it shows you the entire document. Can we get a toggle for this please?

**Comment by pjeby** [comment]
This is the same as issue #70.  You can click "Subscribe" there to receive notification when there are updates on it.
