### ISSUE TITLE
Feature Request：It is hoped that folded nodes can also start floating display

### ISSUE THREAD

**Issue by jiajiala** [nothingislost/obsidian-hover-editor#229]
![Honeycam 2023-08-02 15-54-00](https://github.com/nothingislost/obsidian-hover-editor/assets/73203026/2c585676-ee4b-42b0-b6fe-41def59367df)
like this

**Comment by jiajiala** [comment]
![image](https://github.com/nothingislost/obsidian-hover-editor/assets/73203026/0bc9be23-25a1-431f-b2e2-5eda9accb77e)

**Comment by jiajiala** [comment]
This way I can fold most of the content and use the floating window to quickly view it when I need to

It's great for clarifying your mind and writing long articles

**Comment by pjeby** [comment]
There isn't really a way to do this in Hover Editor, as Obsidian stores all the folding for a note in one place, and applies it whenever you open the note.  Hover Editor opens the note, so you get the same folding as in the other place where the note is.

**Comment by jiajiala** [comment]
Today, I noticed that I folded the node, but the node can still display its children in the embedded block, and I wonder if this can be a breakthrough
like this
![image](https://github.com/nothingislost/obsidian-hover-editor/assets/73203026/81a1e53a-e24a-4ea3-9b1c-f1508fab8467)

**Comment by jiajiala** [comment]
> There isn't really a way to do this in Hover Editor, as Obsidian stores all the folding for a note in one place, and applies it whenever you open the note. Hover Editor opens the note, so you get the same folding as in the other place where the note is.
Today, I noticed that I folded the node, but the node can still display its children in the embedded block, and I wonder if this can be a breakthrough
like this
image

**Comment by pjeby** [comment]
Hover Editor is just a tab that floats over the rest of the workspace.  If it doesn't work in a plain tab, it won't work in Hover Editor.

And in plain tabs, if you want to see what's in a fold, you have to unfold it.
