### ISSUE TITLE
Frequent TypeErrors in console when rapidly changing hover targets

### ISSUE THREAD

**Issue by pjeby** [nothingislost/obsidian-hover-editor#23]
If I move my mouse rapidly up and down over a document in my sidebar with lots of links, a gradually increasing number of these errors occur in the console:

```
TypeError: Cannot read properties of null (reading 'path')
    at e.set (app.js:1:1197063)
    at t.setViewData (app.js:1:1544440)
    at t.setData (app.js:1:1232084)
    at t.<anonymous> (app.js:1:1231987)
    at app.js:1:127083
    at Object.next (app.js:1:127188)
    at s (app.js:1:125927)
```

This appears to indicate a race condition where closing the popup before it is finished loading causes Obsidian to try to process the loaded data in a no-longer functional leaf.  It looks like maybe detach() should check to see if the leaf is `.working`, and if so defer the detach until completion before actually detaching.  

This is not the only such TypeError that can occur, btw, but it's the most reproducible one.  Here are some others:

```
app.js:formatted:58622 Uncaught TypeError: Cannot read properties of null (reading 'onResize')
    at re.t.onResize (app.js:1:1280665)
    at a (app.js:1:233024)

app.js:formatted:58522 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'setEphemeralState')
    at re.t.setEphemeralState (app.js:1:1278551)
    at re.<anonymous> (app.js:1:1278242)
    at app.js:1:127083
    at Object.next (app.js:1:127188)
    at s (app.js:1:125927)
```

In both of these cases, the error is the leaf trying to do something to a view that doesn't exist.  But I don't know how to reproduce them, and it's possible that they stem from the same source, anyway, just failing in a different part of the code,

**Comment by nothingislost** [comment]
We're kind of stress testing the rapid fire creation of leafs & views here which is something I don't think Licat expects to happen often :) The main cause seems to be the lack of a null check on onResize. This reduces the number of issues pretty considerably

```js
  onResize(): void {
    // the native obsidian method does not do a null check on this.view
    this.view?.onResize();
  }
```

However the path issue is definitely a race condition. `this.working` didn't seem to be sufficient so I added two new checks `this.opening` and `this.detaching` to make sure those two actions don't intersect. With this setup I haven't been able to replicate any exceptions so far.

**Comment by pjeby** [comment]
Nice!  I will look forward to the release.

**Comment by nothingislost** [comment]
https://github.com/nothingislost/obsidian-hover-editor/releases/tag/0.3.5 is now available. Let me know how it goes when you have a chance to check it out.

Thanks again for the feedback and testing. Much appreciated!

**Comment by pjeby** [comment]
Looks like it works!  Hovered all the things and no errors in console.
