### ISSUE TITLE
[Issue] When using the command "open link under cursor in new hover editor" my cursor doesnt move to the new hover editor 

### ISSUE THREAD

**Issue by CrackheadoooObsidianUserooo** [nothingislost/obsidian-hover-editor#231]
# Video 
- https://github.com/nothingislost/obsidian-hover-editor/assets/121588624/65dcbac2-f87e-4344-b19e-8dca1d7b914d

**Comment by pjeby** [comment]
In your "Editor" settings in Obsidian, what do you have set as the "Default view for new tabs"?

Also, can you reproduce this issue in the sandbox vault with only Hover Editor enabled?  I'm currently not able to reproduce this problem at all.  I can get it to open in reading mode or editing mode, and if it opens in editing mode the cursor appears and is focused.

**Comment by CrackheadoooObsidianUserooo** [comment]
Ive just disable every Plugin except Hover Editor and then reanabled some, to find out which causese the Problem. Its make.md. Ive then disabled all internal settings of make.md but it sitill doesnt work. My resoultion is now to disable make.md. It is a common "bug" that is known under the make.md community. (it is documented from the author itself on the make.md discord under  the channel improvement)
