### ISSUE TITLE
Feature Request：When I minimize the window and it's still big, I want it to shrink to the bottom and arrange it

### ISSUE THREAD

**Issue by jiajiala** [nothingislost/obsidian-hover-editor#235]
like this
![image](https://github.com/nothingislost/obsidian-hover-editor/assets/73203026/020605cc-973c-48ca-9c55-c5a01c02c671)
Click the Minimize button, and the window automatically shrinks to the bottom to become a TAB

And want to have shortcuts to all zoom out and all zoom in on these Windows

**Comment by pjeby** [comment]
Please stop opening duplicate issues.  There is already an open request for this feature, which you can find by searching the issues for "minimize".
