### ISSUE TITLE
Support hover editor for canvas card

### ISSUE THREAD

**Issue by KuiyueRO** [nothingislost/obsidian-hover-editor#237]
Can the hover editor support canvas cards?
![image](https://github.com/nothingislost/obsidian-hover-editor/assets/63145205/15995d5d-d367-4725-9570-7b7651be1fdf)

---
# What do I want

![image](https://github.com/nothingislost/obsidian-hover-editor/assets/63145205/543450f8-93b4-4b4e-bc61-94207a788e1f)
![image](https://github.com/nothingislost/obsidian-hover-editor/assets/63145205/7882c708-e3ba-47f9-bd60-775d9a6bd461)

In heptabase, we can split notes in the sidebar to edit.

In obsidian, we can use hover editor plugin to get the same feature.
1. open in hover editor
2. snap active hover editor to right

But hover editor is only used for notes in canvas, not for cards, So I want to ask if it is possible to support cards.

Thanks. : )

**Comment by pjeby** [comment]
If you're asking whether you can hover links that are in a canvas card, the answer is that you can, but you have to click the card once first in order to unfreeze the card.  While the card is frozen you can't interact with it except to drag or resize it, so there's no way for HE to know you are hovering over it.  Once you click the card you can hover as many links in it as you like.

**Comment by KuiyueRO** [comment]
No,I mean hover card is like hover notes.I think I didn't make it clear so I re-edited the question
![image](https://github.com/nothingislost/obsidian-hover-editor/assets/63145205/8ee567e0-6d1b-46ad-87ff-b218a2092433)

**Comment by pjeby** [comment]
All Hover Editor does is provide a "tab" that floats, so if you can't do it with a regular tab, you can't do it with Hover Editor.  Obsidian would need to have a built-in ability to show a card in a tab for Hover Editor to be able to do it -- but it sounds like really the feature you want is to be able to show a card in a tab to begin with.  So probably you should make a feature request on the Obsidian forums for that.

**Comment by KuiyueRO** [comment]
Thank you for your patient answer.
