### ISSUE TITLE
0.11.15 The floating window is blocking my search box

### ISSUE THREAD

**Issue by jiajiala** [nothingislost/obsidian-hover-editor#247]
A recent update made the floating window obscure my search box
![image](https://github.com/nothingislost/obsidian-hover-editor/assets/73203026/c73f8fac-2990-424a-bf4a-9232ea7ebdc9)
![image](https://github.com/nothingislost/obsidian-hover-editor/assets/73203026/705e7961-d16f-4b84-922c-b1bbaed66e32)
This search du is also very useful for me, hopefully the two are compatible
![image](https://github.com/nothingislost/obsidian-hover-editor/assets/73203026/96b791b9-7072-43fd-82a8-6cb69347003d)

**Comment by pjeby** [comment]
Well, that's a side effect of changing hover editor to fix your problem with ordering of hover editors.  If you want the floating search to be above all your hover editors, you'll need to use CSS to set its z-index higher than that of the hover editors.  I believe 42 should be high enough to float above everything except the active hover editor and anything you're currently hovering.

Unfortunately, Obsidian does not provide any built-in features for plugins to co-operate about this sort of thing.  Also, there is nothing that Hover Editor can do to avoid this except to use a lower z-index... but then you would have the other problem back again.
