### ISSUE TITLE
Feature Request：The length of the suspended window according to the article

### ISSUE THREAD

**Issue by jiajiala** [nothingislost/obsidian-hover-editor#248]
The idea came from another piece of software, Roamedit

When the suspended window is triggered, the length of its display changes with the length of the article, which can save time

As shown in the figure
![Honeycam 2023-11-08 17-01-05](https://github.com/nothingislost/obsidian-hover-editor/assets/73203026/1c5e9598-dd4e-4e01-9e96-4f7ea0c718c1)

Then there is a bug that the default expansion of the floating window of the current plug-in cannot exceed 1000, and the value above 1000 is invalid

**Comment by pjeby** [comment]
Please see #243 for why this is not compatible with Hover Editor's features.  (Short version: many things you can view in a Hover Editor don't *have* a size, so there is no way to determine what size it should be.)
