### ISSUE TITLE
The floating window does not display the title of the document

### ISSUE THREAD

**Issue by jiajiala** [nothingislost/obsidian-hover-editor#252]
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/73203026/b27eaad3-d3ce-42e9-aabc-9779c12b0805)
I used the embedded document feature in EXcalidraw
As shown, when using the floating window, the embedded title disappears
It seems to be caused by the following
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/73203026/23699e04-c02a-4242-8961-7d754e183dc6)
When I turn this option off, it will work, but I don't know if there will be any other bugs

**Comment by pjeby** [comment]
Inline titles are disabled by default to save space; you can of course use different CSS to re-enable it in embedded documents if you so choose.

**Comment by jiajiala** [comment]
Here are the solutions left to others who encounter the same problem
Put this css block into your obsidian

`/*导致标题无法显示*/ .hover-popover .inline-title, .inline-embed .inline-title { display: flex; }/*修复又会导致 嵌入块在md里 额外多一个标题号*/ /*禁用嵌入标题*/ .markdown-embed-title, .markdown-embed .mod-header+ div > :is(h1, h2, h3, h4, h5, h6) { display: none; }`
