### ISSUE TITLE
How to use mouse button to open a new window in the original window?

### ISSUE THREAD

**Issue by chenbihao** [nothingislost/obsidian-hover-editor#253]
How to use mouse button to open a new window in the original window?

Just like obsidian native operation  use left mouse button or ctrl + left mouse button

![image](https://github.com/nothingislost/obsidian-hover-editor/assets/21167262/541ffc5d-688b-44fc-be23-13dc25239dbc)

**Comment by pjeby** [comment]
You can drag a link to the tab bar to open a new tab there.

**Comment by chenbihao** [comment]
> You can drag a link to the tab bar to open a new tab there.您可以将链接拖动到标签栏以在其中打开一个新标签页。

Wow, I learned something new today. Thank you for your guidance.
