### ISSUE TITLE
[FR] Customizable hotkeys for triggering on embeds?

### ISSUE THREAD

**Issue by yett1873** [nothingislost/obsidian-hover-editor#255]
Hi, so the editor is always triggered unexpectedly, especially when copying selected texts from embeds (holding ⌘C and hovering over the embed). Closing the editor with ⌘W would also trigger the editor and reopen the closed window if one does not move the cursor away from the embed area within the Hover Trigger Delay. 
Would it be possible to allow for less frequently used modifier keys such as ALT or function keys?

**Comment by pjeby** [comment]
No - the modifier key is determined by Obsidian, not Hover Editor.  I suggest disabling autofocus and/or "Trigger hover preview on embeds" in the Hover Editor settings.

**Comment by yett1873** [comment]
> No - the modifier key is determined by Obsidian, not Hover Editor. I suggest disabling autofocus and/or "Trigger hover preview on embeds" in the Hover Editor settings.

Got it, thanks for your instructions!
