### ISSUE TITLE
Feature / Bug - open current file in a new hover editor not working on not basic notes

### ISSUE THREAD

**Issue by Mistmage** [nothingislost/obsidian-hover-editor#257]
Originally I thought it was a problem with sides or kanban plugin.
But soon I understood that not the case:

"Open current file in a new hover editor" command / hotkey work fine on notes, no matter where they are.
But anything else (I tried canvas, kanban board and an open gate site),
Can be converted using command, or be opened using menu, but not open via command.
I have no idea is it a bug, some weird limitation, but here it is...

**Comment by pjeby** [comment]
Should be fixed in 0.11.16 - it was old code from when Hover Editor didn't support anything that wasn't a markdown file.  It should now work for the currently-active file, regardless of type or whether the "active" file is focused.

**Comment by Mistmage** [comment]
Great! That fixes it. Thank you very much.
