### ISSUE TITLE
Supporting splits

### ISSUE THREAD

**Issue by pjeby** [nothingislost/obsidian-hover-editor#26]
So, I've noticed that although the plugin goes to some lengths to hide split operations, the truth is that you can split using the command palette/hotkeys, and then adjust your split sizes and whatnot.  But closing the other leaves closes the entire popover.

I've made a small patch that allows closing individual leaves within a popover without closing the whole thing, and it works pretty well, with a couple minor limitations: namely, double-clicking collapses all the splits in a way that's a bit ugly if you have a horizontal split in there, and the pin icons don't really do anything on anything but the original leaf.  (Pane relief's commands to move the panes left/right or up/down in their splits also work!)

Would you like a PR?  I think I can flesh things out to properly close everything and get rid of the Array.prototype hack, too.  Pinning is a bit tricky -- ideally the pin would only ever appear on the top/leftmost leaf, but I think that's pretty doable.  And of course the menu filtering (at least for splits) could be removed.

**Comment by nothingislost** [comment]
Yeah, splitting is hidden right now because of exactly what you just mentioned. I haven't got around to making it work well enough to make it visible. Definitely open to a PR that gets the splitting capability stable and adds the split options back to the context menu.

The Array prototype hack is to get to Licat's active popover array since he's managing that already. Were you thinking of just doing our own tracking array? Since you can't iterate popovers with iterateLeaves, it's useful to have them all in an array if you want to do anything programmatic with them.

**Comment by pjeby** [comment]
Yeah, not technically an array but a weakmap from dom elements to popover instances, populated when a popover is created.  Then there's a function, `HoverEdtior.activePopovers()` that scans hover popovers present in the dom and looks them up in the weakmap, returning a list of what it finds.  (See the first commit of #27 for just that part of the changes.)

**Comment by nothingislost** [comment]
There are some folks who are already leveraging the `activePopovers` property on the root of the plugin instance so I'm going to add back:

```js
  get activePopovers(): HoverEditor[] {
    return HoverEditor.activePopovers();
  }
```

unless you see any issues with that.

**Comment by pjeby** [comment]
Wow, really?  Yeah, shouldn't be any problems there, as long as they don't save the list anywhere.  What are they using it for?

**Comment by pjeby** [comment]
(Also, the list only contains HoverEditors, not other popups, in case they were wanting that.)

**Comment by pjeby** [comment]
If he can have the main process filter for `window.open()` allow creating `about:blank` windows, we might be able to try popping out to other windows entirely.  :)

**Comment by pjeby** [comment]
Closing this since #52 will support everything that was intended for this issue (and a fair bit extra).
