### ISSUE TITLE
keybinding for opening a file on a canvas in Hover Editor

### ISSUE THREAD

**Issue by gitacrobat** [nothingislost/obsidian-hover-editor#260]
In the context menu (right click menu) of a selected canvas card is an option to open it in Hover Editor. Is there a way to bind this to a keyboard shortcut?

**Comment by pjeby** [comment]
Hm.  We could probably change the "Hover Editor: Open current file in new Hover Editor" command to work in the case where you're editing the card, but right now it opens the canvas.

**Comment by pjeby** [comment]
This is now implemented in 0.11.17, just released.  If you use the keyboard command for "Hover Editor: Open current file in new Hover Editor" while editing a note embedded in a canvas, it will open that note in a hover editor.

**Comment by gitacrobat** [comment]
Wow!!!! That was fast. So many thanks!
