### ISSUE TITLE
[Feature Request] Add hotkey to trigger hover editor

### ISSUE THREAD

**Issue by Emilorzz** [nothingislost/obsidian-hover-editor#263]
I do not know if this is even possible or if this is the relevant place to post this request, but it would be nice to have to hold a key like CTRL or ALT before the Hover Editor pops up when hovering over links. I reference many PDFs with course material in my university notes, and when just scrolling through my notes, it is a bit annoying having every single PDF pop up.

As a workaround, I have delayed the editor pop up substantially, but it would be much nicer with a hotkey.

Please let me know if I have missed a setting for this, or if the request is entirely unreasonable, thanks.

**Comment by pjeby** [comment]
Go to the Obsidian settings, click on "Page Preview" under **Core Plugins** (not Community).  You will see a list with the title "Require Ctrl to trigger page preview on hover".  Switch on the toggles for each place where you want it to work that way.

It won't require *holding* the key, but it will require you to at least tap the key while hovering for a popup to open.

**Comment by Emilorzz** [comment]
> Go to the Obsidian settings, click on "Page Preview" under **Core Plugins** (not Community). You will see a list with the title "Require Ctrl to trigger page preview on hover". Switch on the toggles for each place where you want it to work that way.
> 
> It won't require _holding_ the key, but it will require you to at least tap the key while hovering for a popup to open.

Thank you! I totally missed that.
