### ISSUE TITLE
conflict with Obisidian core pluglin page preview

### ISSUE THREAD

**Issue by trencyclopedia** [nothingislost/obsidian-hover-editor#270]
I like this hover editor plugin very much before, but since I updated my obisidan to 1.4.16, which has a similar core plugin named page preview, this plugin doesn't work well anymore. 

I assume there are some conflicts in the CSS or other relavent settings of these two plugins. But I have no idea where the problem are and how to solve it. 

I tried to enable/disable one or both plugins, and only keep one active, but the issues doesn't get solved.

**Comment by trencyclopedia** [comment]
I saw the disclaimer of the developer.

**Comment by pjeby** [comment]
I'm confused - I use the plugin with Obsidian 1.5.8 and it works fine.  What specific problem are you having?  (Obsidian has had a core page preview plugin since 0.12 and this plugin has always been a tool to replace/enhance it.)
