### ISSUE TITLE
Installing Hover Editor changes the default Quick Switcher (Obsidian v1.6.0)

### ISSUE THREAD

**Issue by trainbuffer** [nothingislost/obsidian-hover-editor#274]
Ok, so here's a weird one:

In the v1.6.0 Sandbox, `Ctrl + O` to open the Quick Switcher. All good. 

![Screenshot 2024-05-10 075023](https://github.com/nothingislost/obsidian-hover-editor/assets/3751726/f26f6a09-32f8-4e25-af3b-9f5a1b4c82f7)

Install and enable _Hover Editor_ (no settings changed):

![Screenshot 2024-05-10 075109](https://github.com/nothingislost/obsidian-hover-editor/assets/3751726/77697124-6d12-4541-b111-9160afc56394)

Where did the Quick Switcher bottom row of options go? 😁

Obsidian Sandbox v1.6.0 / 1.5.8 installer / Windows 11

**Comment by pjeby** [comment]
1.6 has a whole bunch of changes in CSS, presumably in support of RTL text.  I already found and fixed a different CSS issue today, I'll look into this later.  My guess is that they either made the bottom region fixed in size or it's something to do with wrapping.

**Comment by pjeby** [comment]
Hm.  Not CSS.  Looks like a change in how the .setInstructions() API works, though I imagine the change may be RTL-related.  Will have to dig deeper on this one.

**Comment by pjeby** [comment]
Ok,  should be fixed in HE 0.11.19.  Let me know if there are any issues.

**Comment by trainbuffer** [comment]
Looks great. It wasn't a showstopper, but unexpected for sure. 

Thanks for your prompt reply with this, and for all the great plugins you made or look after.
