### ISSUE TITLE
[BUG] V0.11.20  can not work in obsidian V1.6.3

### ISSUE THREAD

**Issue by cloudherder** [nothingislost/obsidian-hover-editor#277]
V0.11.20  can not work in obsidian V1.6.3 , hover editor window can not popup while mouse hover all link.

**Comment by pjeby** [comment]
I'm not experiencing this with 1.6.3.  Can you repro in sandbox with stock theme, no other plugins + snippets?  Also please supply debug info (platform, installer version, etc.)

**Comment by cloudherder** [comment]
> I'm not experiencing this with 1.6.3. Can you repro in sandbox with stock theme, no other plugins + snippets? Also please supply debug info (platform, installer version, etc.)

I have tried the conditions you pointed out, and the hover editor can run normally. It seems to be caused by other issues.
