### ISSUE TITLE
[Question] Is it possible to use Hover Editor and the new footnote popup feature?

### ISSUE THREAD

**Issue by trainbuffer** [nothingislost/obsidian-hover-editor#283]
From Obsidian v1.7+, there's: 

- You can now create new footnotes by clicking on the hover preview of a footnote ID.

It wasn't working properly, but Obsidian v.1.7.2 seems to have sorted it out. 

![Screenshot 2024-09-21 at 10 10 35](https://github.com/user-attachments/assets/a7b962b0-9a27-4bd0-b576-3c0992bc321b)

With Hover Editor installed:

![Screenshot 2024-09-21 at 10 11 34](https://github.com/user-attachments/assets/69036058-c527-406a-b7be-8192b8371047)

I'm wondering if it will, at some point, be possible to use this new vanilla footnote feature  when hovering on footnotes and Hover Editor when hovering on links, etc. 

Thanks!

**Comment by mjknght** [comment]
I second this! Hover editor breaks the popover for footnotes written inline too, e.g.

`^[This is a footnote]`

Would be great if popovers for both footnote styles could work as expected.

**Comment by trainbuffer** [comment]
As of Hover Editor v0.11.21, options for triggering (or not) Hover Editor on block links and footnotes look like options now.
