### ISSUE TITLE
"Support opening links in the main window when in  the hover window"

### ISSUE THREAD

**Issue by DZL1943** [nothingislost/obsidian-hover-editor#288]

**Comment by pjeby** [comment]
Drag the link to the tab where you want it to open, or between tabs to open it as a new tab.

Alternately, you can use Obsidian's pinning feature to pin the hover editor (assuming it has focus), and then links will go to the most recently-active unpinned tab.  (Note: this has nothing to do with the pin icon on the hover editor, it's Obsidian's "Toggle pin" command.)
