### ISSUE TITLE
Possibility to use Ctrl + hover in the sidebar 

### ISSUE THREAD

**Issue by Kayfum** [nothingislost/obsidian-hover-editor#294]
Hi,
Great plugin!
It would be perfect if there was an option to use Ctrl + hover over the link, especially in the sidebar.

Otherwise, when you search for a document in the sidebar, a popup appears hiding the name and it's difficult to open the document in the app.

Thanks a lot!!

**Comment by pjeby** [comment]
In Obsidian's configuration under the **Core** Plugins section (not community), select Page Preview.  There will be a bank of toggles there you can set to control whether ctrl is required in different parts of the app.
