### ISSUE TITLE
FR: Add popover minimize/maximize/restore controls/commands

### ISSUE THREAD

**Issue by nothingislost** [nothingislost/obsidian-hover-editor#34]
Currently you can only minimize using the somewhat hidden double click on header functionality. This would add additional icons (possibly when you hover the pin icon?) and registered commands to invoke these actions.

**Comment by cumany** [comment]
Is it possible to minimize note to icons and maximize it when clicking on the hover icon?
![Uploading memos2.gif…]()

**Comment by pjeby** [comment]
It might be nice to have the proposed controls be part of a (thicker, more visible) frame around the leaf, that is clearly distinct from the leaf/leaves it encloses.  Among other things, it would visually separate "drag this group of things" from "drag this one particular thing so I can rearrange things."

**Comment by nothingislost** [comment]
Yeah, I've thought about that outer frame but it seems clunky from a UI design perspective. I like how minimal the panes are right now but maybe there's a way to do this that isn't clunky/obtrusive like only showing the outer frame on hover or something.

**Comment by nothingislost** [comment]
Here's a quick mock up of what that outer frame might look like 
![image](https://user-images.githubusercontent.com/89109712/158884654-539638de-190f-491a-af0f-70e405c3f0b9.png)

It complicates the minimize logic since it currently minimizes to this:

![image](https://user-images.githubusercontent.com/89109712/158884866-3b5857aa-1c7c-4222-8a37-e0f91ee3c120.png)

I could shrink the height further but then you wouldn't have any indication of what was open inside of the popover, due to the file title being hidden away.

**Comment by pjeby** [comment]
I'd actually like a thick frame all the way around for resizing -- currently resizing is a huge pain to pinpoint the one or two pixels that actually work.  :wink:  And if the top bar and frame only appear when the popover as a whole is hovered, then it won't be adding to the minimization issues.

It'd be nice to be able to resize from the sides as well - I frequently find myself trying to drag them to widen or narrow a popup.

On the positive side, I like the concept and the way it looks, though I kind of wish the pin were more to the left, i.e. that the document icon doesn't sit right under it and is more obviously part of the window contents vs the outer frame.  The frame having a different background color (even if just a subtle shade difference) would probably also help with that.  Though I'd also be fine with a high-contrast approach, like if the bar is dark when the window's light and vice versa, or the outer controls are primary colors and the inner are monochrome.

But yeah, I'm stoked for this even if the initial version is just letting us include the document icons away from the pin.  Not only will it mean drag rearrangement but we'll also be able to get rid of the crazy pin positioning logic I added recently.  :wink:

**Comment by pjeby** [comment]
Actually, a thick frame isn't technically required; have a look at https://jspanel.de/ - the demo that pops up can be resized from all sides fairly well, even from slightly outside the edges so it's not a precision mousing endeavor precisely at the corners.

**Comment by nothingislost** [comment]
Hey, the resize handle is 4px I'll have you know ;) I agree with most of those points though. Thanks for the jspanel example. I can make interactjs work pretty much exactly like that. I turned off side resizing back when I was running into leaf side resizing conflicts and just never turned it back on.

My design goals/challenges for this are as follows:
- Allow popover dragging via the popover title without interfering with the ability to rename the document title
- Allow for intuitive leaf dragging without interfering with popover interactions
- Make the popover pin action intuitive and distinct from the native leaf control functionality
- Resize from all sides and corners easily while not interfering with things like the scroll bar or nav bar actions
- Keep the UI fairly minimal and adhere to native Obsidian design standards as much as possible
- Ensure that any newly added UI elements do not badly break community themes
- Ensure design decisions are compatible with mobile or have mobile specific alternatives (two finger drag to move, pinch to resize, etc)
- Allow for rolling the window up to just show the title bar while still giving some indication of what the popover contains

**Comment by pjeby** [comment]
Well, if the frame isn't the same as the title bar, and the frame doesn't appear unless hover or focus is inside the popup, that at least solves a *couple* of those issues.  And I think this will be a popular enough thing that the themes will get fixed; trying to work in all the themes with zero breakage may well be too constraining.  (E.g. whatever you do will probably at least partly break the windows 98 theme  :wink: )

Still, it's gonna be awesome.  When I feel up to coding again I'm thinking of taking a whack at that quick switcher extra key to open in a popup... and maybe a modifed quick switcher that previews files as you type, ala QE.  :-)

**Comment by nothingislost** [comment]
Delivered in 0.6.0

**Comment by pjeby** [comment]
I see the version bump in git, but there doesn't appear to be a release yet?

**Comment by nothingislost** [comment]
Oops, forgot to remove the pre release flag. Thanks!
