### ISSUE TITLE
Bug: resize when minimized

### ISSUE THREAD

**Issue by zcysxy** [nothingislost/obsidian-hover-editor#46]
How to reproduce:

1. Open a hover editor
2. Double click to minimize it
3. Resize the nav bar horizontally
4. Double click won't restore the hover editor then

**Comment by nothingislost** [comment]
Thanks for the report. This will be addressed in the next release.

**Comment by nothingislost** [comment]
This should be fixed in 0.4.4

**Comment by zcysxy** [comment]
Thanks for the quick fix!

I notice that 0.44 adds an `!important` background to the `view-header`, which may not be compatible with some themes.

<img width="650" alt="image" src="https://user-images.githubusercontent.com/48207708/159104787-965f9664-97a5-4252-8512-f88f0f8fc5ac.png">

This is how it looks when I change the background to `transparent`, and everything works fine

<img width="656" alt="image" src="https://user-images.githubusercontent.com/48207708/159104757-576d9172-79f5-432a-9e15-72fe66efc814.png">
