### ISSUE TITLE
Text lines cannot be selected

### ISSUE THREAD

**Issue by zhl111** [nothingislost/obsidian-hover-editor#53]
Problems with selection after snap to edges
minimal theme
![image](https://user-images.githubusercontent.com/29135984/159410905-09b7199f-9432-419c-8f2d-dec059edfb2c.png)

**Comment by nothingislost** [comment]
Please provide a more thorough explanation of the issue or video of you reproducing it.

**Comment by zhl111** [comment]
![动画](https://user-images.githubusercontent.com/29135984/159421147-2bdc61b3-1dd8-4e1a-bcc7-64fe62ccdc94.gif)

**Comment by zhl111** [comment]
I see,It's the problem with snippets
![image](https://user-images.githubusercontent.com/29135984/159426084-9a305b9f-1840-4e7f-821c-6df082b4e497.png)
