### ISSUE TITLE
FR: Show backlinks by default

### ISSUE THREAD

**Issue by dcoales** [nothingislost/obsidian-hover-editor#55]
Fantastic plugin - thank you.   Makes a huge difference to my workflow.

Any chance we could have an option to show backlinks by default inside the popovers.

**Comment by nothingislost** [comment]
Hmm, that should be doable. I'll take a look.

**Comment by pjeby** [comment]
FYI, you can turn on the "Backlinks in document" setting in the "Backlinks" settings page, and it'll work for all panes, including popovers.
