### ISSUE TITLE
 The value of the data-path attribute shows undefined

### ISSUE THREAD

**Issue by cumany** [nothingislost/obsidian-hover-editor#59]
no-markdown type views cannot get the value of data-path, such as the memos plugin：

`<div class="popover-title" data-path="undefined">memos</div>`

with the latest version 0.6.0

**Comment by nothingislost** [comment]
Thanks for the heads up

**Comment by nothingislost** [comment]
Can you explain why this is an issue for you? data-path is getting defined to deal with file renaming properly but a memos view will never get renamed as it has no direct file association. I can remove the attribute all together when the value is undefined but that's about it.

**Comment by cumany** [comment]
Well, I just want to define the style of different windows depending on the data-path. Of course it would be better if the data-title class property could be defined in the hover-popover class. so  I can define different hover styles for different title windows

**Comment by nothingislost** [comment]
What I'm planning on doing is raising the active view type up to the .hover.editor class as per #57. Do you think that would fit your needs?

**Comment by cumany** [comment]
Yes, it would be great if it worked.

**Comment by nothingislost** [comment]
This was added in https://github.com/nothingislost/obsidian-hover-editor/releases/tag/0.7.0

**Comment by cumany** [comment]
Thanks, it worked very well
