### ISSUE TITLE
No pop-ups when hovering over headings in Outline pane

### ISSUE THREAD

**Issue by DutchPete** [nothingislost/obsidian-hover-editor#63]
The plug-in works fine for links within the note, but when hovering over a heading in the Outline pane no pop-up appears (anymore?) when holding down the ⌘/ctrl key. Is that by design?

**Comment by nothingislost** [comment]
The Outline pane does not appear to be a valid hover source, even for the native page preview functionality. So, this would be a feature request to allow Outline plugin headings to be hover previewable.

**Comment by DutchPete** [comment]
I noticed that glbal search results are also hoverable, which is good. Between that and the links I don't need more so won't submit a feature request.
I'll close the issue.
