### ISSUE TITLE
Auto Focus when opening pane via hotkeys

### ISSUE THREAD

**Issue by orand** [nothingislost/obsidian-hover-editor#65]
Auto Focus doesn't currently work when opening a pane via an assigned hotkey, such as "open link under cursor in new popover".  The focus currently remains on the parent window, requiring you to use the mouse to set the focus, which kind of defeats the point of using a keyboard shortcut.

**Comment by nothingislost** [comment]
Confirmed. Thanks for the report.

**Comment by orand** [comment]
Confirmed fixed in the latest release.  That was fast!  Thank you!
