### ISSUE TITLE
FR:  Add a command to send the active popover pane directly into the native root split

### ISSUE THREAD

**Issue by creadian** [nothingislost/obsidian-hover-editor#66]
Hi, I love hover editor!   I would find it supremely useful if there was a button that turns a hover window into a pane. If I have too many hover editors open, the view can get scattered, and I may choose to make them 'permanent' by opening them in a pane.

Thank you!

**Comment by nothingislost** [comment]
There's already the ability to drag hover editor panes into the main workspace as shown in the demo video in the readme. Are you aware of that ability? It provides a bit more flexibility as you can be precise about where the pane gets placed within the workspace. If there was a button, I would have to stick it somewhere indiscriminately :)

**Comment by Obadiahcruz** [comment]
what do you think about allowing the esc key to cancel the movement of the pane? the only way to cancel the movement of the pane in to the main workspace is to move the cursor back to where you first had it @nothingislost

**Comment by creadian** [comment]
🙀 Oooooh I didn't realize you could drag panes *out* of the hover editor window into the main workspace! That didn't get clear to me from the demo video, and that is amazing. In case you did want to create a button, it could either by default add the pane to the right of the last pane, or if another pane is highlighted and I click the button in hover editor, the new pane could be added next the the previously highlighted one. 
Either way, I am happy with the existing funtionality. This allows me to quickly jump back and forth between hover editor window and a static pane (I constantly have ca. 10 panes open using sliding panes).
Thanks again for your awesome work!

**Comment by pjeby** [comment]
There is now a command and menu item to  "Dock Hover Editor to workspace", and as of Obsidian 0.15.x, the escape key works to cancel pane dragging, so I think that covers everything that was requested in this issue.  (You can even drag panes from hover editors out to the desktop to open them as a new window now, which will also make them "permanent".)
