### ISSUE TITLE
Support spawning popovers outside of the main electron window

### ISSUE THREAD

**Issue by Connor-yang96** [nothingislost/obsidian-hover-editor#7]
It's really great plugin ,speed up for editing. 

and, I found it's inside of frame. We have to maximize obsidian, 

Is there a possible put hover-editor outside of obsidian's frame ? 

![image](https://user-images.githubusercontent.com/81000027/157379911-ab6f5431-aca8-476c-85af-c56155f578d5.png)

I guess this need talk with licat about electron for implement this feature ?

**Comment by wenlzhang** [comment]
It would be great if this can be supported. This way, one can temporarily present a popover note during a meeting.

**Comment by nothingislost** [comment]
This would indeed be very cool but it's going to take some low level electron work to make happen. You can create a new electron window easy enough but the new window is a separate process and cross process communication is difficult to manage.

If someone could write an electron extension that could manage to open a new electron window that shared the same main thread process, this might be doable but I wouldn't expect that any time soon :)

**Comment by pjeby** [comment]
This is now possible with the Obsidian 0.15.3 Insider build: you can drag a popover leaf outside the main window and drop it to open a new window with that leaf, or use the new builtin menu item to "open in new window".

(Note: you will need to upgrade to the Hover Editor 0.10.4 beta release, as well as Obsidian 0.15.3.)
