### ISSUE TITLE
Add CSS class to specify plugin is active

### ISSUE THREAD

**Issue by kepano** [nothingislost/obsidian-hover-editor#76]
As far as I can tell there is no CSS class on the body or the popover itself that indicates the plugin is active. This means that styling can affect the regular popovers when Hover Editor is off. It would be helpful to have a class for this to be able to target the plugin.

**Comment by nothingislost** [comment]
I've been looking at this for so long that I thought .hover-popover was mine... I'll get this sorted and document the styling recommendations.

**Comment by nothingislost** [comment]
This was added in https://github.com/nothingislost/obsidian-hover-editor/releases/tag/0.7.1
