### ISSUE TITLE
The problem of using Hover Editor and Sliding Panes together

### ISSUE THREAD

**Issue by oslog** [nothingislost/obsidian-hover-editor#78]
When multiple panels are open, moving the mouse over a link will open another panel.

![bug](https://user-images.githubusercontent.com/3367160/160823527-385118ed-fead-4270-a55c-0091cb8b2c4d.gif)

**Comment by kithairon** [comment]
Very neat plug-in and impressively useful! In awe of all the functionality you've packed into this. 
I'm a great fan of Sliding Panes and experience various forms of breakdown described [here](https://forum.obsidian.md/t/sliding-panes-andy-matuschak-mode-plugin/7652/127?u=marc-a) when use your plugin with Hover Editor and Sliding Panes with more than 12 panes. I'm on the latest macOS, 32GB RAM Obsidian v.0.14.5 and 0.7.3 of your plugin.
I've eliminated possible interference of themes (it also happens in the default theme) and ticked off the possible interplay of Hover Ed. with other plug-ins. I conclude it's the combination of Hover Editor and Sliding Panes with more than 12 panes open. While I can totally live with this limitation, I thought it may be useful for you to know this.

**Comment by nothingislost** [comment]
@kithairon please see if v0.8.2 improves the situation at all
