### ISSUE TITLE
Option for empty pane

### ISSUE THREAD

**Issue by kmaustral** [nothingislost/obsidian-hover-editor#8]
This is a wonderful plug-in that adds a whole new dimension to Obsidian. 

But I find myself still looking for something similar that is in Roam, where you can open an empty pop-up window. Often I need to check or edit something temporarily but it is not a link on the present pane. It would be great to be able to open an empty pane and then use the quick switcher to open the required page. 

You've opened up many possibilities.

**Comment by red-co** [comment]
The current compromise is that you can search or in Explorer open a new pane,(it can work )

**Comment by kmaustral** [comment]
Amazing. I'll share that tip.

**Comment by nothingislost** [comment]
This option is now available in https://github.com/nothingislost/obsidian-hover-editor/releases/tag/0.3.0

**Comment by kmaustral** [comment]
Great. If I try to old a file with the popover in focus, it opens the file
in the main pane, not the popover.

But if I open a new file in the popover, then the switcher works.

Let me know if I can help.

Thanks
Kevin

**Comment by nothingislost** [comment]
Yeah, that appears to be a core Obsidian bug. It has been raised with Licat and I'll see if I can patch it myself for now.

**Comment by nothingislost** [comment]
https://github.com/nothingislost/obsidian-hover-editor/releases/tag/0.3.6 should improve the "go to file" behavior when invoked on an empty popover

**Comment by kmaustral** [comment]
Works perfectly!
