### ISSUE TITLE
can not open new note at the main page if the existing page is pinned and another page is hovered

### ISSUE THREAD

**Issue by Xieleilab** [nothingislost/obsidian-hover-editor#81]
if note A is not hovered and is pinned, while note B is hovered, under this circumstances if i choose note A, and open another obsidian url in zotero， the new page will be opened in the position of note B, but normally it should automatically create a new page besides note A

**Comment by nothingislost** [comment]
This is not clear. Please rephrase this and provide more detail. Ideally include screenshots or a video of the behavior being described.

**Comment by nothingislost** [comment]
@Xieleilab I think this should be resolved in v0.8.2
