### ISSUE TITLE
FR: Hotkey for opening link under cursor using hover editor

### ISSUE THREAD

**Issue by HEmile** [nothingislost/obsidian-hover-editor#9]
One workflow that would be very useful to keyboard-first users would be if there was a configurable hotkey for opening the link under the cursor using the hover editor. It's already possible to run other commands inside the hover editor, including the one to close the pane to return to the normal editor, so there's no need to add a command for _closing_ the editor.

**Comment by MILKMILKKING** [comment]
+1

**Comment by nothingislost** [comment]
This option is now available in https://github.com/nothingislost/obsidian-hover-editor/releases/tag/0.3.0

**Comment by HEmile** [comment]
Thank you, this seems to work well! One thing that doesn't seem to always work for me though is that the hover editor usually doesn't get the keyboard focus, meaning I still need the mouse to give it focus.

https://user-images.githubusercontent.com/1289165/157833344-4c01cb21-5618-42c8-9774-f5234ca2f438.mov

**Comment by HEmile** [comment]
Absolutely perfect, thank you so much!
