### ISSUE TITLE
Remove "does not work without page preview" notice

### ISSUE THREAD

**Issue by chrisgrieser** [nothingislost/obsidian-hover-editor#90]
it works just fine without it, you only have to manually create a hover editor via context menu or command (which I personally prefer)

**Comment by nothingislost** [comment]
Fair enough. Will remove on the next release.

**Comment by chrisgrieser** [comment]
oh, I also noticed that the Hover Editor seems to enable the Page Preview Core plugin, even if I have disable it?

**Comment by nothingislost** [comment]
Yep, I noticed that while looking into this. That will also be fixed next release.

**Comment by nothingislost** [comment]
This is now resolved in v0.8.2
