### ISSUE TITLE
[Feature Request] Snap to Edges: Keyboard Hotkeys navigation

### ISSUE THREAD

**Issue by FelipeRearden** [nothingislost/obsidian-hover-editor#92]
Hello @nothingislost !!!!!

My FR is simple to explain: 4 new commands to the Command Palette to make possible to use the feature `Snap to Edges` with a the keyboard.
- Snap to Right
- Snap to Left
- Full Screen
- Restore
  
I have two of many users cases to share:

**The first one** is obvious :) to organize my popovers while writing 

**The second one** is to define an specific behavior to some special notes that I want/need to them to be placed in fixed place always.

My idea is to use QuickAdd MACRO to open a specific note in popover mode at a specific place (right, left or full screen).
- My classic case would be to open my QuickNote.md note to not forget about things came to my mind that exactly moment.

---

Thanks for reading this!!!!

Have a great day!!!!!

**Comment by nothingislost** [comment]
This is now available in 0.8.6

**Comment by FelipeRearden** [comment]
Working perfect on version 0.8.7 -> Obsidian 0.14.2 (Last Public Release)

Thank you very much @nothingislost . You are an Obsidian Legend 

Thank you for making our Obsidian dreams come true everyday :1st_place_medal:
