### ISSUE TITLE
[BUG REPORT] The hover editors will be auto closed when I click the file in the background.

### ISSUE THREAD

**Issue by johnnzhang** [nothingislost/obsidian-hover-editor#93]
When the hover editors are pinned, they will be auto closed when I click the file in the background.
This bug appeared after version 0.7.1.
Version 0.7.0 works well.

**Comment by nothingislost** [comment]
This needs more details and replication steps. I can not replicate this behavior with this level of detail.

**Comment by johnnzhang** [comment]
"Split vertically" or "Split horizontally" can also replicate the bug.
Please see the following gif.
![split](https://user-images.githubusercontent.com/16620514/162023242-7ee2a097-4232-4554-b2d2-741bba2d540e.gif)

**Comment by pjeby** [comment]
Can you include all your Hover Editor settings for the above examples?  I can't reproduce this with my settings.

**Comment by johnnzhang** [comment]
The settings are as follows:

```json
{
  "defaultMode": "preview",
  "autoPin": "onMove",
  "triggerDelay": 300,
  "closeDelay": 600,
  "autoFocus": true,
  "rollDown": false,
  "snapToEdges": false,
  "initialHeight": "340px",
  "initialWidth": "400px",
  "showViewHeader": false
}
```

Besides, I find if I open a hover editor in the command palette： ctrl + p -> open new popover， this bug won't appear.

**Comment by nothingislost** [comment]
@johnnzhang if you're a user of the BRAT plugin, please try checking for updates and see if the latest v0.8.1 release resolves the issue you're seeing here

**Comment by generic-user** [comment]
@nothingislost I can confirm the issue is not resolved by installing version 0.8.1

I really want to take the opportunity to congratulate and thank you on your work on this plugin. It is a huge game changer for Obsidian.

**Comment by nothingislost** [comment]
@generic-user thanks for the input. Can you provide your operating system version and your obsidian installer version (under settings -> about -> installer version)?

**Comment by nothingislost** [comment]
This is definitely an installer version issue, I'm just not sure exactly why yet. Please grab and install an updated installer from https://obsidian.md and see if that helps.

**Comment by nothingislost** [comment]
Looks like it's my use of AbortSignal in one of the event handlers which was only added in Chrome 90

**Comment by pjeby** [comment]
There's a fix in 0.8.2 for this, so please give it a try.  (Also it would be a very good idea to update your Obsidian installers anyway; you can currently download 0.14.5 from https://obsidian.md/ .)

**Comment by generic-user** [comment]
Hi, thanks for the fix 🎉 

I can confirm the issue has been resolved on my end. 

For completeness, some info about  the environment I tested in.
```
OS: Windows Version 1909 (OS Build 18363.2158)
Obsidian installer version: 0.14.5
Obsidian application version: 0.14.5
```
> Also it would be a very good idea to update your Obsidian installers anyway

Thanks for the heads-up, I had no idea the installer did not update itself.

**Comment by johnnzhang** [comment]
Thanks for your excellent work.
I reinstall the obsidian and update the plugin.
The hover editor works well.

But the displayed version in Obsidian is 0.7.3.
Is the "version" in the manifest file not updated?

**Comment by nothingislost** [comment]
@johnnzhang yeah, my fault, the release didn't get an updated manifest.json. it should be fixed now. thanks for pointing that out.

**Comment by johnnzhang** [comment]
Thanks to all of you.
The issue has been resolved completely, and I'll close it.
