### ISSUE TITLE
[FR] Optimize for collaborating with third-party plugin media-extended

### ISSUE THREAD

**Issue by XMB-7** [nothingislost/obsidian-hover-editor#95]
For a common MD file, there is an option to open this file in a popover.
However, when opening a video in a new pane via media-extended, no corresponding option out there to put it in a popover or convert it into a popover.
![图片](https://user-images.githubusercontent.com/65625632/162038125-1e116925-c765-485f-b054-1c4acd292666.png)

**Comment by nothingislost** [comment]
Sure, I'll handle this. You can close your issue in the media extended repo.

**Comment by XMB-7** [comment]
@nothingislost Thanks, this would further impove my experience when taking video notes. I've closed the same issues in other repos.

**Comment by nothingislost** [comment]
This is available in 0.8.2 if you want to check it out and report back

**Comment by XMB-7** [comment]
Thanks for the enhancement, but currently when opening the video pane in a popover, it will lose the link to the note pane, so cannot add timestamps as expected.
![图片](https://user-images.githubusercontent.com/65625632/163297875-35e2a9cb-907b-4535-a95c-ae40fc7d8dc7.png)
![图片](https://user-images.githubusercontent.com/65625632/163298141-332d9d80-c9f5-4875-a285-4e8db5d0328f.png)

I think it would be better if it could be further optimized like below. The video pane could directly convert into a popover, meanwhile, it would not lose the link to the note pane.
![图片](https://user-images.githubusercontent.com/65625632/163298402-0f1462c3-34e3-45b1-ad19-d3bb3430c5dc.png)

**Comment by nothingislost** [comment]
Ah, I'm not very familiar with the media extended plugin so I didn't test much beyond being able to show the menu item.

One option here is that you can manually relink that hover editor with your document using the context menu. Not ideal but at least the functionality is there.

I like the idea of having an option to convert a leaf to a hover editor. You can already do this but it's not as convenient as a "Convert pane to a Hover Editor" command. See the video for an example:

https://user-images.githubusercontent.com/89109712/163299960-68722dbd-d1c9-40a2-ac7c-1e3284c13f25.mp4

**Comment by XMB-7** [comment]
Well, my current workaround is to open the video pane in a popover, I think this one is better than the others.
![图片](https://user-images.githubusercontent.com/65625632/163301460-df46ddc2-a618-4905-9c66-badb6a87edf5.png)

Anyway, still looking forward to a new plugin feature that an existing pane to be converted to a popover. It would much benefit all workflows, not only when collaborating with media-extended.

**Comment by nothingislost** [comment]
If you're using the BRAT plugin, check for beta updates and you should get 0.8.4 which has the "Convert pane to Hover Editor" command and context menu item.

**Comment by XMB-7** [comment]
That's pretty awesome! And a little bit more suggestion is, for a popover that has been converted this way, to have a command and a context menu item to convert it back. Really appreciate your time and effort in this.

**Comment by nothingislost** [comment]
You can just drag the pane back into the workspace to accomplish that though right? 

Assuming there's a need for the context menu item, where would you expect the pane to be placed within the workspace?

**Comment by XMB-7** [comment]
Sure, but sometimes I prefer to achieve this only by the keyboard.
I think it could be placed horizontally next to the active pane, just like the behavior when ctrl+cliking on a file to open it in a new pane.

**Comment by nothingislost** [comment]
Alright, 0.8.5 adds the "Dock Hover Editor to workspace" command and context menu item.
