### ISSUE TITLE
Feature Request: Hover embedded files and blocks

### ISSUE THREAD

**Issue by kazdonkai** [nothingislost/obsidian-hover-editor#99]
Hi,
It would be great if the Hover Editor plugin could be activated from the link mark of an embedded file or block!

Sorry if this has already been requested.

![181CD466-6F12-47E1-996C-8CE6A9AE343C](https://user-images.githubusercontent.com/90127278/162767282-7973591d-b1f1-44c8-b975-d6b70964564c.jpeg)

**Comment by nothingislost** [comment]
Yeah, it's on my radar to allow this for all embeds. I have it working for images already (unreleased) and should be able to add block embeds shortly.

**Comment by nothingislost** [comment]
If you're using BRAT, the 0.9.0 beta has this functionality. Note that the entire embed can trigger a hover preview, not just the link icon.

**Comment by tadashi-aikawa** [comment]
Hi, @nothingislost, thank you for such an awesome plugin! I use v0.9.0.

Can I open a hover popup only when I hover an image (or internal embed) with pressing with `Ctrl/Cmd` key?

Currently, It shows a hover popup when the mouse cursor passes through the image each time, and they are almost unintended. It would be great if there was anything that would suppress them :)

**Comment by nothingislost** [comment]
Hi @tadashi-aikawa the modifier key settings are configured under the "Page preview" core plugin setting page. Make sure you have all of the options enabled: 
![image](https://user-images.githubusercontent.com/89109712/163677685-00af032d-6f69-4aaf-ac4a-8ab7055642a1.png)

If that still doesn't work, let me know,

**Comment by kazdonkai** [comment]
I can now hover on the embed block, but I want it to hover only when the cursor is over the link mark.

**Comment by nothingislost** [comment]
> I can now hover on the embed block, but I want it to hover only when the cursor is over the link mark.

Can you explain your use case for only wanting it to trigger over the link icon?

**Comment by tadashi-aikawa** [comment]
@nothingislost 
Thank you for reply!

My settings are as follows.

![image](https://user-images.githubusercontent.com/9500018/163680123-b97ceed4-f135-4637-9f35-80e3c741da93.png)

In the case of the internal link, it doesn't show a popup without pressing with `Ctrl/Cmd` key. This is what I expected. However, in the case of the image, it shows a popup without pressing with `Ctrl/Cmd` key.

[Without pressing with `Ctrl/Cmd` key]
https://user-images.githubusercontent.com/9500018/163680322-90ecd563-985e-4d96-8e69-16f58684298f.mp4

[Pressing with `Ctrl/Cmd` key]
https://user-images.githubusercontent.com/9500018/163680370-6bd6a0dc-d089-4d31-91c7-d8a0be4ad66a.mp4

**Comment by nothingislost** [comment]
@tadashi-aikawa ah, that is because all rendered markdown is considered "Reading view", even if it's rendered in Live Preview mode. I'll see what I can do to change that behavior to make things more consistent.

**Comment by nothingislost** [comment]
@tadashi-aikawa https://github.com/nothingislost/obsidian-hover-editor/releases/tag/0.9.1 should fix that. it was a bug on my part. thanks for the report.

**Comment by tadashi-aikawa** [comment]
@nothingislost 
Works perfectly! Thanks for your quick work!

**Comment by kazdonkai** [comment]
> > I can now hover on the embed block, but I want it to hover only when the cursor is over the link mark.
> 
> Can you explain your use case for only wanting it to trigger over the link icon?

Right now, I think it pops up anywhere in the embedded text, but this is because it is annoying when referring to or copying text.

Even in the note ground text, it only pops up at the links.
I would like to request that you could restrict the same so that only link symbols pop up.

**Comment by nothingislost** [comment]
@kazdonkai If you set the modifier keys in the Page Preview plugin settings as shown a few replies up, the popover won't show on hover unless you first press cmd/ctrl. Is that not sufficient for your use case?

**Comment by kazdonkai** [comment]
> @kazdonkai If you set the modifier keys in the Page Preview plugin settings as shown a few replies up, the popover won't show on hover unless you first press cmd/ctrl. Is that not sufficient for your use case?

Hmm, surely by using the cmd/ctrl keys we can limit the popups.
I usually find that click a hassle, so I always let it pop up.
Which one we choose is a matter of preference, but here I would like to follow the author's policy.

Anyway, I believe that this feature has made possible or exceeded, on a personal level, the transclusion envisioned by Theodore Nelson. Thanks for a great plugin!
